keys:
    - &look 8A6971471CF700C1DA530A2787F4DAF30B83AC70
    - &yumiko 83BE2CD0BB979BE4C5B7DF22873AB85C69865BEF

creation_rules:
    - path_regex: .*common\.yaml$
      key_groups:
          - pgp:
                - *look
                - *yumiko
    - path_regex: .*yumiko\.yaml$
      key_groups:
          - pgp:
                - *look
                - *yumiko
    - path_regex: .*yuria\.yaml$
      key_groups:
          - pgp:
                - *look
