#!/bin/sh

HOOK_DIR="$(dirname "$0")/post-merge.d"

if [ -d "$HOOK_DIR" ]; then
    for hook in "$HOOK_DIR"/*; do
        if [ -x "$hook" ]; then
            # echo "Running $(basename "$hook")..."
            "$hook" "$@"
            if [ $? -ne 0 ]; then
                exit 1
            fi
        fi
    done
fi
