(put 'with-transformation 'scheme-indent-function 1)

(put 'nonguix-container 'scheme-indent-function 0)
(put 'nvidia-configuration 'scheme-indent-function 0)

;; Configurations below are copied from Guix.
(setopt indent-tabs-mode nil)

;; Emacs 28 changed the behavior of 'lisp-fill-paragraph', which causes the
;; first line of package descriptions to extrude past 'fill-column', and
;; somehow that is deemed more correct upstream (see:
;; https://issues.guix.gnu.org/56197).
(progn
  (require 'lisp-mode)
  (defun emacs27-lisp-fill-paragraph (&optional justify)
    (interactive "P")
    (or (fill-comment-paragraph justify)
        (let ((paragraph-start
               (concat paragraph-start
                       "\\|\\s-*\\([(;\"]\\|\\s-:\\|`(\\|#'(\\)"))
              (paragraph-separate
               (concat paragraph-separate "\\|\\s-*\".*[,\\.]$"))
              (fill-column (if (and (integerp emacs-lisp-docstring-fill-column)
                                    (derived-mode-p 'emacs-lisp-mode))
                               emacs-lisp-docstring-fill-column
                             fill-column)))
          (fill-paragraph justify))
        ;; Never return nil.
        t))
  (setq-local fill-paragraph-function #'emacs27-lisp-fill-paragraph))

;; This notably allows '(' in Paredit to not insert a space when the
;; preceding symbol is one of these.
(modify-syntax-entry ?~ "'")
(modify-syntax-entry ?$ "'")
(modify-syntax-entry ?+ "'")

(put 'eval-when 'scheme-indent-function 1)
(put 'call-with-prompt 'scheme-indent-function 1)
(put 'test-assert 'scheme-indent-function 1)
(put 'test-assertm 'scheme-indent-function 1)
(put 'test-equalm 'scheme-indent-function 1)
(put 'test-equal 'scheme-indent-function 1)
(put 'test-eq 'scheme-indent-function 1)
(put 'call-with-input-string 'scheme-indent-function 1)
(put 'call-with-port 'scheme-indent-function 1)
(put 'guard 'scheme-indent-function 1)
(put 'lambda* 'scheme-indent-function 1)
(put 'substitute* 'scheme-indent-function 1)
(put 'match-record 'scheme-indent-function 3)
(put 'match-record-lambda 'scheme-indent-function 2)

;; TODO: Contribute these to Emacs' scheme-mode.
(put 'let-keywords 'scheme-indent-function 3)

;; 'modify-inputs' and its keywords.
(put 'modify-inputs 'scheme-indent-function 1)
(put 'replace 'scheme-indent-function 1)

;; 'modify-phases' and its keywords.
(put 'modify-phases 'scheme-indent-function 1)
(put 'replace 'scheme-indent-function 1)
(put 'add-before 'scheme-indent-function 2)
(put 'add-after 'scheme-indent-function 2)

(put 'modify-services 'scheme-indent-function 1)
(put 'with-directory-excursion 'scheme-indent-function 1)
(put 'with-file-lock 'scheme-indent-function 1)
(put 'with-file-lock/no-wait 'scheme-indent-function 1)
(put 'with-profile-lock 'scheme-indent-function 1)
(put 'with-writable-file 'scheme-indent-function 2)

(put 'package/inherit 'scheme-indent-function 1)
(put 'substitute-keyword-arguments 'scheme-indent-function 1)
(put 'with-store 'scheme-indent-function 1)
(put 'with-store/non-blocking 'scheme-indent-function 1)
(put 'with-external-store 'scheme-indent-function 1)
(put 'with-error-handling 'scheme-indent-function 0)
(put 'with-mutex 'scheme-indent-function 1)
(put 'with-atomic-file-output 'scheme-indent-function 1)
(put 'call-with-compressed-output-port 'scheme-indent-function 2)
(put 'call-with-decompressed-port 'scheme-indent-function 2)
(put 'call-with-gzip-input-port 'scheme-indent-function 1)
(put 'call-with-gzip-output-port 'scheme-indent-function 1)
(put 'call-with-lzip-input-port 'scheme-indent-function 1)
(put 'call-with-lzip-output-port 'scheme-indent-function 1)
(put 'signature-case 'scheme-indent-function 1)
(put 'emacs-batch-eval 'scheme-indent-function 0)
(put 'emacs-batch-edit-file 'scheme-indent-function 1)
(put 'emacs-substitute-sexps 'scheme-indent-function 1)
(put 'emacs-substitute-variables 'scheme-indent-function 1)
(put 'with-derivation-narinfo 'scheme-indent-function 1)
(put 'with-derivation-substitute 'scheme-indent-function 2)
(put 'with-status-report 'scheme-indent-function 1)
(put 'with-status-verbosity 'scheme-indent-function 1)
(put 'with-build-handler 'scheme-indent-function 1)

(put 'mlambda 'scheme-indent-function 1)
(put 'mlambdaq 'scheme-indent-function 1)
(put 'syntax-parameterize 'scheme-indent-function 1)
(put 'with-monad 'scheme-indent-function 1)
(put 'mbegin 'scheme-indent-function 1)
(put 'mwhen 'scheme-indent-function 1)
(put 'munless 'scheme-indent-function 1)
(put 'mlet* 'scheme-indent-function 2)
(put 'mlet 'scheme-indent-function 2)
(put 'state-parameterize 'scheme-indent-function 2)
(put 'store-parameterize 'scheme-indent-function 2)
(put 'run-with-store 'scheme-indent-function 1)
(put 'run-with-state 'scheme-indent-function 1)
(put 'wrap-program 'scheme-indent-function 1)
(put 'wrap-script 'scheme-indent-function 1)
(put 'with-imported-modules 'scheme-indent-function 1)
(put 'with-extensions 'scheme-indent-function 1)
(put 'with-parameters 'scheme-indent-function 1)
(put 'let-system 'scheme-indent-function 1)
(put 'with-build-variables 'scheme-indent-function 2)

(put 'with-database 'scheme-indent-function 2)
(put 'call-with-database 'scheme-indent-function 1)
(put 'call-with-transaction 'scheme-indent-function 1)
(put 'call-with-retrying-transaction 'scheme-indent-function 1)

(put 'call-with-container 'scheme-indent-function 1)
(put 'container-excursion 'scheme-indent-function 1)
(put 'eventually 'scheme-indent-function 1)

(put 'call-with-progress-reporter 'scheme-indent-function 1)
(put 'with-repository 'scheme-indent-function 2)
(put 'with-temporary-git-repository 'scheme-indent-function 2)
(put 'with-environment-variables 'scheme-indent-function 1)
(put 'with-fresh-gnupg-setup 'scheme-indent-function 1)

(put 'with-paginated-output-port 'scheme-indent-function 1)

(put 'with-shepherd-action 'scheme-indent-function 3)

(put 'with-http-server 'scheme-indent-function 1)

;; Record constructors.
;; URIs for origin methods.
(put 'android-repo-reference 'scheme-indent-function 0)
(put 'bzr-reference 'scheme-indent-function 0)
(put 'cvs-reference 'scheme-indent-function 0)
(put 'git-checkout 'scheme-indent-function 0)
(put 'git-reference 'scheme-indent-function 0)
(put 'hg-reference 'scheme-indent-function 0)
(put 'svn-multi-reference 'scheme-indent-function 0)
(put 'svn-reference 'scheme-indent-function 0)

;; guix/
(put 'avahi-service 'scheme-indent-function 0)
(put 'bag 'scheme-indent-function 0)
(put 'build-status 'scheme-indent-function 0)
(put 'build-system 'scheme-indent-function 0)
(put 'channel 'scheme-indent-function 0)
(put 'gnu-package-descriptor 'scheme-indent-function 0)
(put 'graft 'scheme-indent-function 0)
(put 'lint-checker 'scheme-indent-function 0)
(put 'lint-warning 'scheme-indent-function 0)
(put 'manifest-entry 'scheme-indent-function 0)
(put 'manifest-pattern 'scheme-indent-function 0)
(put 'manifest-transaction 'scheme-indent-function 0)
(put 'node-type 'scheme-indent-function 0)
(put 'origin 'scheme-indent-function 0)
(put 'package 'scheme-indent-function 0)
(put 'platform 'scheme-indent-function 0)
(put 'profile 'scheme-indent-function 0)
(put 'progress-reporter 'scheme-indent-function 0)
(put 'search-path-specification 'scheme-indent-function 0)
(put 'upstream-input 'scheme-indent-function 0)
(put 'upstream-source 'scheme-indent-function 0)
(put 'upstream-updater 'scheme-indent-function 0)

;; gnu/
(put 'bootloader 'scheme-indent-function 0)
(put 'bootloader-configuration 'scheme-indent-function 0)
(put 'image 'scheme-indent-function 0)
(put 'image-type 'scheme-indent-function 0)
(put 'menu-entry 'scheme-indent-function 0)
(put 'partition 'scheme-indent-function 0)

;; gnu/machine
(put 'digital-ocean-configuration 'scheme-indent-function 0)
(put 'environment-type 'scheme-indent-function 0)
(put 'hetzner-configuration 'scheme-indent-function 0)
(put 'machine 'scheme-indent-function 0)
(put 'machine-ssh-configuration 'scheme-indent-function 0)

;; gnu/system
(put 'boot-parameters 'scheme-indent-function 0)
(put 'file-system 'scheme-indent-function 0)
(put 'file-system-mapping 'scheme-indent-function 0)
(put 'locale-definition 'scheme-indent-function 0)
(put 'mapped-device 'scheme-indent-function 0)
(put 'mapped-device-kind 'scheme-indent-function 0)
(put 'name-service 'scheme-indent-function 0)
(put 'name-service-switch 'scheme-indent-function 0)
(put 'operating-system 'scheme-indent-function 0)
(put 'pam-configuration 'scheme-indent-function 0)
(put 'pam-entry 'scheme-indent-function 0)
(put 'pam-extension 'scheme-indent-function 0)
(put 'pam-service 'scheme-indent-function 0)
(put 'privileged-program 'scheme-indent-function 0)
(put 'subid-range 'scheme-indent-function 0)
(put 'subids-configuration 'scheme-indent-function 0)
(put 'subids-extension 'scheme-indent-function 0)
(put 'swap-space 'scheme-indent-function 0)
(put 'user-account 'scheme-indent-function 0)
(put 'user-group 'scheme-indent-function 0)
(put 'virtual-machine 'scheme-indent-function 0)

;; gnu/home
(put 'home-bash-configuration 'scheme-indent-function 0)
(put 'home-bash-extension 'scheme-indent-function 0)
(put 'home-batsignal-configuration 'scheme-indent-function 0)
(put 'home-beets-configuration 'scheme-indent-function 0)
(put 'home-dbus-configuration 'scheme-indent-function 0)
(put 'home-dotfiles-configuration 'scheme-indent-function 0)
(put 'home-environment 'scheme-indent-function 0)
(put 'home-fish-configuration 'scheme-indent-function 0)
(put 'home-fish-extension 'scheme-indent-function 0)
(put 'home-gpg-agent-configuration 'scheme-indent-function 0)
(put 'home-inputrc-configuration 'scheme-indent-function 0)
(put 'home-kodi-configuration 'scheme-indent-function 0)
(put 'home-mcron-configuration 'scheme-indent-function 0)
(put 'home-msmtp-configuration 'scheme-indent-function 0)
(put 'home-openssh-configuration 'scheme-indent-function 0)
(put 'home-parcimonie-configuration 'scheme-indent-function 0)
(put 'home-pipewire-configuration 'scheme-indent-function 0)
(put 'home-redshift-configuration 'scheme-indent-function 0)
(put 'home-shell-profile-configuration 'scheme-indent-function 0)
(put 'home-shepherd-configuration 'scheme-indent-function 0)
(put 'home-ssh-agent-configuration 'scheme-indent-function 0)
(put 'home-unclutter-configuration 'scheme-indent-function 0)
(put 'home-xdg-base-directories-configuration 'scheme-indent-function 0)
(put 'home-xdg-mime-applications-configuration 'scheme-indent-function 0)
(put 'home-xdg-user-directories-configuration 'scheme-indent-function 0)
(put 'home-xmodmap-configuration 'scheme-indent-function 0)
(put 'home-znc-configuration 'scheme-indent-function 0)
(put 'home-zsh-configuration 'scheme-indent-function 0)
(put 'home-zsh-extension 'scheme-indent-function 0)
(put 'msmtp-account 'scheme-indent-function 0)
(put 'msmtp-configuration 'scheme-indent-function 0)
(put 'openssh-host 'scheme-indent-function 0)
(put 'point 'scheme-indent-function 0)
(put 'proxy-jump 'scheme-indent-function 0)
(put 'sway-bar 'scheme-indent-function 0)
(put 'sway-border-color 'scheme-indent-function 0)
(put 'sway-color 'scheme-indent-function 0)
(put 'sway-configuration 'scheme-indent-function 0)
(put 'sway-input 'scheme-indent-function 0)
(put 'sway-mode 'scheme-indent-function 0)
(put 'sway-output 'scheme-indent-function 0)
(put 'xdg-desktop-action 'scheme-indent-function 0)
(put 'xdg-desktop-entry 'scheme-indent-function 0)

;; gnu/services
(put 'agate-configuration 'scheme-indent-function 0)
(put 'agetty-configuration 'scheme-indent-function 0)
(put 'alsa-configuration 'scheme-indent-function 0)
(put 'anonip-configuration 'scheme-indent-function 0)
(put 'apcupsd-configuration 'scheme-indent-function 0)
(put 'apcupsd-event-handlers 'scheme-indent-function 0)
(put 'auditd-configuration 'scheme-indent-function 0)
(put 'autossh-configuration 'scheme-indent-function 0)
(put 'avahi-configuration 'scheme-indent-function 0)
(put 'backend-userroot-configuration 'scheme-indent-function 0)
(put 'bffe-configuration 'scheme-indent-function 0)
(put 'bitlbee-configuration 'scheme-indent-function 0)
(put 'bluetooth-configuration 'scheme-indent-function 0)
(put 'cachefilesd-configuration 'scheme-indent-function 0)
(put 'certbot-configuration 'scheme-indent-function 0)
(put 'cgit-configuration 'scheme-indent-function 0)
(put 'configuration-field 'scheme-indent-function 0)
(put 'connman-configuration 'scheme-indent-function 0)
(put 'connman-general-configuration 'scheme-indent-function 0)
(put 'containerd-configuration 'scheme-indent-function 0)
(put 'cuirass-configuration 'scheme-indent-function 0)
(put 'cuirass-remote-server-configuration 'scheme-indent-function 0)
(put 'cuirass-remote-worker-configuration 'scheme-indent-function 0)
(put 'cups-configuration 'scheme-indent-function 0)
(put 'darkstat-configuration 'scheme-indent-function 0)
(put 'dbus-configuration 'scheme-indent-function 0)
(put 'dconf-keyfile 'scheme-indent-function 0)
(put 'dconf-profile 'scheme-indent-function 0)
(put 'debootstrap-configuration 'scheme-indent-function 0)
(put 'dhcp-client-configuration 'scheme-indent-function 0)
(put 'dhcpcd-configuration 'scheme-indent-function 0)
(put 'dhcpd-configuration 'scheme-indent-function 0)
(put 'dicod-configuration 'scheme-indent-function 0)
(put 'dict-configuration 'scheme-indent-function 0)
(put 'directory-server-instance-configuration 'scheme-indent-function 0)
(put 'dnsmasq-configuration 'scheme-indent-function 0)
(put 'docker-configuration 'scheme-indent-function 0)
(put 'dovecot-configuration 'scheme-indent-function 0)
(put 'dropbear-configuration 'scheme-indent-function 0)
(put 'earlyoom-configuration 'scheme-indent-function 0)
(put 'elogind-configuration 'scheme-indent-function 0)
(put 'enlightenment-desktop-configuration 'scheme-indent-function 0)
(put 'exim-configuration 'scheme-indent-function 0)
(put 'ext-component-configuration 'scheme-indent-function 0)
(put 'fail2ban-configuration 'scheme-indent-function 0)
(put 'fail2ban-ignore-cache-configuration 'scheme-indent-function 0)
(put 'fail2ban-jail-action-configuration 'scheme-indent-function 0)
(put 'fail2ban-jail-configuration 'scheme-indent-function 0)
(put 'fail2ban-jail-filter-configuration 'scheme-indent-function 0)
(put 'fcgiwrap-configuration 'scheme-indent-function 0)
(put 'fifo-listener-configuration 'scheme-indent-function 0)
(put 'file-database-configuration 'scheme-indent-function 0)
(put 'files-configuration 'scheme-indent-function 0)
(put 'fprintd-configuration 'scheme-indent-function 0)
(put 'fstrim-configuration 'scheme-indent-function 0)
(put 'ganeti-cleaner-configuration 'scheme-indent-function 0)
(put 'ganeti-confd-configuration 'scheme-indent-function 0)
(put 'ganeti-configuration 'scheme-indent-function 0)
(put 'ganeti-kvmd-configuration 'scheme-indent-function 0)
(put 'ganeti-luxid-configuration 'scheme-indent-function 0)
(put 'ganeti-metad-configuration 'scheme-indent-function 0)
(put 'ganeti-mond-configuration 'scheme-indent-function 0)
(put 'ganeti-noded-configuration 'scheme-indent-function 0)
(put 'ganeti-os 'scheme-indent-function 0)
(put 'ganeti-os-variant 'scheme-indent-function 0)
(put 'ganeti-rapi-configuration 'scheme-indent-function 0)
(put 'ganeti-watcher-configuration 'scheme-indent-function 0)
(put 'ganeti-wconfd-configuration 'scheme-indent-function 0)
(put 'gdm-configuration 'scheme-indent-function 0)
(put 'geoclue-configuration 'scheme-indent-function 0)
(put 'getmail-configuration 'scheme-indent-function 0)
(put 'getmail-configuration-file 'scheme-indent-function 0)
(put 'getmail-destination-configuration 'scheme-indent-function 0)
(put 'getmail-options-configuration 'scheme-indent-function 0)
(put 'getmail-retriever-configuration 'scheme-indent-function 0)
(put 'git-daemon-configuration 'scheme-indent-function 0)
(put 'git-http-configuration 'scheme-indent-function 0)
(put 'gitile-configuration 'scheme-indent-function 0)
(put 'gitolite-configuration 'scheme-indent-function 0)
(put 'gitolite-git-configuration 'scheme-indent-function 0)
(put 'gitolite-rc-file 'scheme-indent-function 0)
(put 'gmnisrv-configuration 'scheme-indent-function 0)
(put 'gnome-desktop-configuration 'scheme-indent-function 0)
(put 'gnome-keyring-configuration 'scheme-indent-function 0)
(put 'gpm-configuration 'scheme-indent-function 0)
(put 'greetd-agreety-session 'scheme-indent-function 0)
(put 'greetd-configuration 'scheme-indent-function 0)
(put 'greetd-gtkgreet-sway-session 'scheme-indent-function 0)
(put 'greetd-terminal-configuration 'scheme-indent-function 0)
(put 'greetd-user-session 'scheme-indent-function 0)
(put 'greetd-wlgreet-configuration 'scheme-indent-function 0)
(put 'greetd-wlgreet-session 'scheme-indent-function 0)
(put 'greetd-wlgreet-sway-session 'scheme-indent-function 0)
(put 'gss-configuration 'scheme-indent-function 0)
(put 'guix-build-coordinator-agent-configuration 'scheme-indent-function 0)
(put 'guix-build-coordinator-agent-dynamic-auth 'scheme-indent-function 0)
(put 'guix-build-coordinator-agent-dynamic-auth-with-file 'scheme-indent-function 0)
(put 'guix-build-coordinator-agent-password-auth 'scheme-indent-function 0)
(put 'guix-build-coordinator-agent-password-file-auth 'scheme-indent-function 0)
(put 'guix-build-coordinator-configuration 'scheme-indent-function 0)
(put 'guix-configuration 'scheme-indent-function 0)
(put 'guix-data-service-configuration 'scheme-indent-function 0)
(put 'guix-extension 'scheme-indent-function 0)
(put 'guix-publish-configuration 'scheme-indent-function 0)
(put 'gvfs-configuration 'scheme-indent-function 0)
(put 'host 'scheme-indent-function 0)
(put 'hostapd-configuration 'scheme-indent-function 0)
(put 'hpcguix-web-configuration 'scheme-indent-function 0)
(put 'httpd-config-file 'scheme-indent-function 0)
(put 'httpd-configuration 'scheme-indent-function 0)
(put 'httpd-module 'scheme-indent-function 0)
(put 'httpd-virtualhost 'scheme-indent-function 0)
(put 'hurd-console-configuration 'scheme-indent-function 0)
(put 'hurd-getty-configuration 'scheme-indent-function 0)
(put 'hurd-vm-configuration 'scheme-indent-function 0)
(put 'idmap-configuration 'scheme-indent-function 0)
(put 'imap4d-configuration 'scheme-indent-function 0)
(put 'inet-listener-configuration 'scheme-indent-function 0)
(put 'inetd-configuration 'scheme-indent-function 0)
(put 'inetd-entry 'scheme-indent-function 0)
(put 'inputattach-configuration 'scheme-indent-function 0)
(put 'int-component-configuration 'scheme-indent-function 0)
(put 'ipfs-configuration 'scheme-indent-function 0)
(put 'iptables-configuration 'scheme-indent-function 0)
(put 'iwd-configuration 'scheme-indent-function 0)
(put 'iwd-general-settings 'scheme-indent-function 0)
(put 'iwd-network-settings 'scheme-indent-function 0)
(put 'iwd-scan-settings 'scheme-indent-function 0)
(put 'iwd-settings 'scheme-indent-function 0)
(put 'jami-account 'scheme-indent-function 0)
(put 'jami-configuration 'scheme-indent-function 0)
(put 'joycond-configuration 'scheme-indent-function 0)
(put 'keepalived-configuration 'scheme-indent-function 0)
(put 'kmscon-configuration 'scheme-indent-function 0)
(put 'knot-acl-configuration 'scheme-indent-function 0)
(put 'knot-configuration 'scheme-indent-function 0)
(put 'knot-key-configuration 'scheme-indent-function 0)
(put 'knot-keystore-configuration 'scheme-indent-function 0)
(put 'knot-policy-configuration 'scheme-indent-function 0)
(put 'knot-remote-configuration 'scheme-indent-function 0)
(put 'knot-resolver-configuration 'scheme-indent-function 0)
(put 'knot-zone-configuration 'scheme-indent-function 0)
(put 'krb5-configuration 'scheme-indent-function 0)
(put 'krb5-realm 'scheme-indent-function 0)
(put 'kwallet-configuration 'scheme-indent-function 0)
(put 'ladspa-configuration 'scheme-indent-function 0)
(put 'laminar-configuration 'scheme-indent-function 0)
(put 'libvirt-configuration 'scheme-indent-function 0)
(put 'lightdm-configuration 'scheme-indent-function 0)
(put 'lightdm-gtk-greeter-configuration 'scheme-indent-function 0)
(put 'lightdm-seat-configuration 'scheme-indent-function 0)
(put 'linux-builder-configuration 'scheme-indent-function 0)
(put 'lirc-configuration 'scheme-indent-function 0)
(put 'live-service 'scheme-indent-function 0)
(put 'localed-configuration 'scheme-indent-function 0)
(put 'location-access-control 'scheme-indent-function 0)
(put 'log-cleanup-configuration 'scheme-indent-function 0)
(put 'log-rotation 'scheme-indent-function 0)
(put 'log-rotation-configuration 'scheme-indent-function 0)
(put 'login-configuration 'scheme-indent-function 0)
(put 'lsh-configuration 'scheme-indent-function 0)
(put 'lxqt-desktop-configuration 'scheme-indent-function 0)
(put 'mailbox-configuration 'scheme-indent-function 0)
(put 'mate-desktop-configuration 'scheme-indent-function 0)
(put 'mcron-configuration 'scheme-indent-function 0)
(put 'memcached-configuration 'scheme-indent-function 0)
(put 'method-access-control 'scheme-indent-function 0)
(put 'mingetty-configuration 'scheme-indent-function 0)
(put 'mod-muc-configuration 'scheme-indent-function 0)
(put 'modem-manager-configuration 'scheme-indent-function 0)
(put 'mosquitto-configuration 'scheme-indent-function 0)
(put 'mpd-configuration 'scheme-indent-function 0)
(put 'mpd-output 'scheme-indent-function 0)
(put 'mpd-partition 'scheme-indent-function 0)
(put 'mpd-plugin 'scheme-indent-function 0)
(put 'mumble-server-configuration 'scheme-indent-function 0)
(put 'mumble-server-public-registration-configuration 'scheme-indent-function 0)
(put 'mumi-configuration 'scheme-indent-function 0)
(put 'mumi-package-configuration 'scheme-indent-function 0)
(put 'mympd-configuration 'scheme-indent-function 0)
(put 'mympd-ip-acl 'scheme-indent-function 0)
(put 'mysql-configuration 'scheme-indent-function 0)
(put 'namespace-configuration 'scheme-indent-function 0)
(put 'nar-herder-cached-compression-configuration 'scheme-indent-function 0)
(put 'nar-herder-configuration 'scheme-indent-function 0)
(put 'network-address 'scheme-indent-function 0)
(put 'network-link 'scheme-indent-function 0)
(put 'network-manager-configuration 'scheme-indent-function 0)
(put 'network-route 'scheme-indent-function 0)
(put 'nfs-configuration 'scheme-indent-function 0)
(put 'nftables-configuration 'scheme-indent-function 0)
(put 'nginx-configuration 'scheme-indent-function 0)
(put 'nginx-location-configuration 'scheme-indent-function 0)
(put 'nginx-log-format-configuration 'scheme-indent-function 0)
(put 'nginx-named-location-configuration 'scheme-indent-function 0)
(put 'nginx-server-configuration 'scheme-indent-function 0)
(put 'nginx-upstream-configuration 'scheme-indent-function 0)
(put 'ngircd-channel 'scheme-indent-function 0)
(put 'ngircd-configuration 'scheme-indent-function 0)
(put 'ngircd-global 'scheme-indent-function 0)
(put 'ngircd-limits 'scheme-indent-function 0)
(put 'ngircd-operator 'scheme-indent-function 0)
(put 'ngircd-options 'scheme-indent-function 0)
(put 'ngircd-server 'scheme-indent-function 0)
(put 'ngircd-ssl 'scheme-indent-function 0)
(put 'nix-configuration 'scheme-indent-function 0)
(put 'nscd-cache 'scheme-indent-function 0)
(put 'nscd-configuration 'scheme-indent-function 0)
(put 'nslcd-configuration 'scheme-indent-function 0)
(put 'ntp-configuration 'scheme-indent-function 0)
(put 'ntp-server 'scheme-indent-function 0)
(put 'oci-container-configuration 'scheme-indent-function 0)
(put 'oci-image 'scheme-indent-function 0)
(put 'opaque-cgit-configuration 'scheme-indent-function 0)
(put 'opaque-cups-configuration 'scheme-indent-function 0)
(put 'opaque-dovecot-configuration 'scheme-indent-function 0)
(put 'opaque-prosody-configuration 'scheme-indent-function 0)
(put 'opendht-configuration 'scheme-indent-function 0)
(put 'openntpd-configuration 'scheme-indent-function 0)
(put 'opensmtpd-configuration 'scheme-indent-function 0)
(put 'openssh-configuration 'scheme-indent-function 0)
(put 'openvpn-ccd-configuration 'scheme-indent-function 0)
(put 'openvpn-client-configuration 'scheme-indent-function 0)
(put 'openvpn-remote-configuration 'scheme-indent-function 0)
(put 'openvpn-server-configuration 'scheme-indent-function 0)
(put 'openvswitch-configuration 'scheme-indent-function 0)
(put 'operation-access-control 'scheme-indent-function 0)
(put 'package-database-configuration 'scheme-indent-function 0)
(put 'pagekite-configuration 'scheme-indent-function 0)
(put 'pam-krb5-configuration 'scheme-indent-function 0)
(put 'pam-mount-configuration 'scheme-indent-function 0)
(put 'pam-mount-volume 'scheme-indent-function 0)
(put 'passdb-configuration 'scheme-indent-function 0)
(put 'patchwork-configuration 'scheme-indent-function 0)
(put 'patchwork-database-configuration 'scheme-indent-function 0)
(put 'patchwork-settings-module 'scheme-indent-function 0)
(put 'pcscd-configuration 'scheme-indent-function 0)
(put 'php-fpm-configuration 'scheme-indent-function 0)
(put 'php-fpm-dynamic-process-manager-configuration 'scheme-indent-function 0)
(put 'php-fpm-on-demand-process-manager-configuration 'scheme-indent-function 0)
(put 'php-fpm-static-process-manager-configuration 'scheme-indent-function 0)
(put 'pipefs-configuration 'scheme-indent-function 0)
(put 'plasma-desktop-configuration 'scheme-indent-function 0)
(put 'plugin-configuration 'scheme-indent-function 0)
(put 'policy-configuration 'scheme-indent-function 0)
(put 'polkit-configuration 'scheme-indent-function 0)
(put 'postgresql-config-file 'scheme-indent-function 0)
(put 'postgresql-configuration 'scheme-indent-function 0)
(put 'postgresql-role 'scheme-indent-function 0)
(put 'pounce-configuration 'scheme-indent-function 0)
(put 'power-profiles-daemon-configuration 'scheme-indent-function 0)
(put 'powertop-configuration 'scheme-indent-function 0)
(put 'prometheus-node-exporter-configuration 'scheme-indent-function 0)
(put 'prosody-configuration 'scheme-indent-function 0)
(put 'protocol-configuration 'scheme-indent-function 0)
(put 'pulseaudio-configuration 'scheme-indent-function 0)
(put 'qemu-binfmt-configuration 'scheme-indent-function 0)
(put 'qemu-guest-agent-configuration 'scheme-indent-function 0)
(put 'quassel-configuration 'scheme-indent-function 0)
(put 'radicale-auth-configuration 'scheme-indent-function 0)
(put 'radicale-configuration 'scheme-indent-function 0)
(put 'radicale-encoding-configuration 'scheme-indent-function 0)
(put 'radicale-logging-configuration 'scheme-indent-function 0)
(put 'radicale-rights-configuration 'scheme-indent-function 0)
(put 'radicale-server-configuration 'scheme-indent-function 0)
(put 'radicale-storage-configuration 'scheme-indent-function 0)
(put 'rasdaemon-configuration 'scheme-indent-function 0)
(put 'readymedia-configuration 'scheme-indent-function 0)
(put 'readymedia-media-directory 'scheme-indent-function 0)
(put 'redis-configuration 'scheme-indent-function 0)
(put 'repository-cgit-configuration 'scheme-indent-function 0)
(put 'resize-file-system-configuration 'scheme-indent-function 0)
(put 'restic-backup-configuration 'scheme-indent-function 0)
(put 'restic-backup-job 'scheme-indent-function 0)
(put 'rngd-configuration 'scheme-indent-function 0)
(put 'rootless-podman-configuration 'scheme-indent-function 0)
(put 'rottlog-configuration 'scheme-indent-function 0)
(put 'rpcbind-configuration 'scheme-indent-function 0)
(put 'rshiny-configuration 'scheme-indent-function 0)
(put 'rspamd-configuration 'scheme-indent-function 0)
(put 'rsync-configuration 'scheme-indent-function 0)
(put 'rsync-module 'scheme-indent-function 0)
(put 'samba-configuration 'scheme-indent-function 0)
(put 'screen-locker-configuration 'scheme-indent-function 0)
(put 'sddm-configuration 'scheme-indent-function 0)
(put 'seatd-configuration 'scheme-indent-function 0)
(put 'service-configuration 'scheme-indent-function 0)
(put 'service-type 'scheme-indent-function 0)
(put 'shepherd-action 'scheme-indent-function 0)
(put 'shepherd-configuration 'scheme-indent-function 0)
(put 'shepherd-service 'scheme-indent-function 0)
(put 'slim-configuration 'scheme-indent-function 0)
(put 'snuik-configuration 'scheme-indent-function 0)
(put 'speakersafetyd-configuration 'scheme-indent-function 0)
(put 'spice-vdagent-configuration 'scheme-indent-function 0)
(put 'ssl-configuration 'scheme-indent-function 0)
(put 'static-networking 'scheme-indent-function 0)
(put 'strongswan-configuration 'scheme-indent-function 0)
(put 'sugar-desktop-configuration 'scheme-indent-function 0)
(put 'syncthing-config-file 'scheme-indent-function 0)
(put 'syncthing-configuration 'scheme-indent-function 0)
(put 'syncthing-device 'scheme-indent-function 0)
(put 'syncthing-folder 'scheme-indent-function 0)
(put 'syncthing-folder-device 'scheme-indent-function 0)
(put 'sysctl-configuration 'scheme-indent-function 0)
(put 'syslog-configuration 'scheme-indent-function 0)
(put 'system-log-configuration 'scheme-indent-function 0)
(put 'tailon-configuration 'scheme-indent-function 0)
(put 'tailon-configuration-file 'scheme-indent-function 0)
(put 'thermald-configuration 'scheme-indent-function 0)
(put 'tlp-configuration 'scheme-indent-function 0)
(put 'tor-configuration 'scheme-indent-function 0)
(put 'tor-onion-service-configuration 'scheme-indent-function 0)
(put 'tor-transport-plugin 'scheme-indent-function 0)
(put 'transmission-daemon-configuration 'scheme-indent-function 0)
(put 'udev-configuration 'scheme-indent-function 0)
(put 'udisks-configuration 'scheme-indent-function 0)
(put 'unattended-upgrade-configuration 'scheme-indent-function 0)
(put 'unbound-configuration 'scheme-indent-function 0)
(put 'unbound-remote 'scheme-indent-function 0)
(put 'unbound-server 'scheme-indent-function 0)
(put 'unbound-zone 'scheme-indent-function 0)
(put 'unix-listener-configuration 'scheme-indent-function 0)
(put 'upower-configuration 'scheme-indent-function 0)
(put 'usb-modeswitch-configuration 'scheme-indent-function 0)
(put 'userdb-configuration 'scheme-indent-function 0)
(put 'varnish-configuration 'scheme-indent-function 0)
(put 'virtlog-configuration 'scheme-indent-function 0)
(put 'virtual-build-machine 'scheme-indent-function 0)
(put 'virtualhost-configuration 'scheme-indent-function 0)
(put 'vnstat-configuration 'scheme-indent-function 0)
(put 'webssh-configuration 'scheme-indent-function 0)
(put 'wesnothd-configuration 'scheme-indent-function 0)
(put 'whoogle-configuration 'scheme-indent-function 0)
(put 'wireguard-configuration 'scheme-indent-function 0)
(put 'wireguard-peer 'scheme-indent-function 0)
(put 'wpa-supplicant-configuration 'scheme-indent-function 0)
(put 'wsdd-configuration 'scheme-indent-function 0)
(put 'xe-guest-utilities-configuration 'scheme-indent-function 0)
(put 'xen-guest-agent-configuration 'scheme-indent-function 0)
(put 'xfce-desktop-configuration 'scheme-indent-function 0)
(put 'xorg-configuration 'scheme-indent-function 0)
(put 'xvnc-configuration 'scheme-indent-function 0)
(put 'yggdrasil-configuration 'scheme-indent-function 0)
(put 'zabbix-agent-configuration 'scheme-indent-function 0)
(put 'zabbix-front-end-configuration 'scheme-indent-function 0)
(put 'zabbix-server-configuration 'scheme-indent-function 0)
(put 'zone-entry 'scheme-indent-function 0)
(put 'zone-file 'scheme-indent-function 0)
(put 'zram-device-configuration 'scheme-indent-function 0)
