#+TITLE: guix-aggregator
an automated repository that aggregates many guix dotfiles to be
indexed by GitHub's search. this is updated once a day.

if you find your dotfiles in here and would like it removed, please
feel free to contact me or open a pull request. or if you want to add
your dotfiles instead, also please, PRs are welcome.

* repositories
# BEGIN REPOLIST
| [[repos/aemogie/aetheria]]       | https://github.com/aemogie/aetheria.git         | dev     |
| [[repos/abcdw/rde]]              | https://git.sr.ht/~abcdw/rde                    | master  |
| [[repos/anemofilia/zero]]        | https://codeberg.org/anemofilia/zero.git        | main    |
| [[repos/look/misako]]            | https://codeberg.org/look/misako.git            | main    |
| [[repos/hako/Testament]]         | https://git.boiledscript.com/hako/Testament.git | trunk   |
| [[repos/jjba23/sss]]             | https://codeberg.org/jjba23/sss.git             | trunk   |
| [[repos/divyaranjan/dotfiles]]   | https://codeberg.org/divyaranjan/dotfiles.git   | master  |
| [[repos/wloxyz/guix-configs]]    | https://codeberg.org/wloxyz/guix-configs.git    | main    |
| [[repos/lynn/galahad.git]]       | https://git.transistor.house/lynn/galahad.git   | main    |
| [[repos/ngraves/dotfiles]]       | https://git.sr.ht/~ngraves/dotfiles             | main    |
| [[repos/efraim/guix-config]]     | https://git.sr.ht/~efraim/guix-config           | master  |
| [[repos/SqrtMinusOne/dotfiles]]  | https://github.com/SqrtMinusOne/dotfiles.git    | master  |
| [[repos/boeg/home]]              | https://git.sr.ht/~boeg/home                    | master  |
| [[repos/aartaka/guix-config]]    | https://github.com/aartaka/guix-config          | master  |
| [[repos/jsoo1/dotfiles]]         | https://github.com/jsoo1/dotfiles.git           | release |
| [[repos/polhuang/dotfiles]]      | https://github.com/polhuang/dotfiles            | master  |
| [[repos/SunJukebox/guix-config]] | https://github.com/SunJukebox/guix-config       | master  |
| [[repos/mrh/dotfiles]]           | https://codeberg.org/mrh/dotfiles.git           | trunk   |
| [[repos/krevedkokun/dotfiles]]   | https://git.sr.ht/~krevedkokun/dotfiles         | master  |
# END REPOLIST

* motivation
i found myself frequently going through multiple git forges, some of
which don't have search/grep functionality, trying to find how others
solved certain problems that i was encountering. this is an attempt to
aggregate useful guix dotfiles and other guix related projects, so i
can easily find examples.

* cloning
as this repository might be large, for cloning for the purpose of
making edits, i recommend these command which clones everything
excluding the ~repos/~ subdirectory
#+BEGIN_SRC sh
  git clone --depth=1 --filter=tree:0 --sparse --no-checkout https://github.com/aemogie/guix-aggregator.git
  cd guix-aggregator
  git sparse-checkout set --no-cone "/*" "!repos/"
  git checkout
#+END_SRC
+ ~--depth=1~ :: shallow clones only the last commit
+ ~--filter=tree:0~ :: partial clone, ensures that no trees are cloned
  at all on first clone. the fetching happens lazily whenever you
  checkout files. ~--filter=blob:none~ would also work if you want the
  trees to be fetched, but not the file contents.
+ ~--sparse~ :: initializes the repository to be a sparse-checkout. by
  default this checks-out the toplevel directory, without recursng
  into any subdirectories. this is often good enough if you're only
  modifying one of these files.
+ ~--no-checkout~ :: this is optional, and more aggressive in that it
  forces sparse to not even checkout the very top level directory
  either which is the default behaviour.
if using ~--no-checkout~ the ~git clone~ should only fetch a single
object, similar to the sample output below.

#+BEGIN_EXAMPLE
Cloning into 'guix-aggregator'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (1/1), done.
#+END_EXAMPLE

if you didn't include ~--no-checkout~ and already have the file you
want to edit, then the next two commands are not relevant. otherwise, we
further configure the already initialized sparse checkout to include
everything *but* the ~repos/~ subdirectory. finally we run ~git
checkout~ to ask git to finally checkout what we have requested.
