"theme" = "anemofilia"

# anemofilia theme {
   "theme.anemofilia.static_bar"             = false
   "theme.anemofilia.default_indicator"      = ""
   "theme.anemofilia.bar_style.bg"           = "▃"
   "theme.anemofilia.bar_style.fg"           = "▃"
   "theme.anemofilia.bar_style.indicator"    = "▃"
   "theme.anemofilia.bar_style.bottom"       = "‾"
   "theme.anemofilia.bar_low.front"          = 0
   "theme.anemofilia.bar_low.back"           = -1
   "theme.anemofilia.bar_mid.front"          = 0
   "theme.anemofilia.bar_mid.back"           = -1
   "theme.anemofilia.bar_high.front"         = 0
   "theme.anemofilia.bar_high.back"          = -1
   "theme.anemofilia.volume_low"             = 4
   "theme.anemofilia.volume_mid"             = 4
   "theme.anemofilia.volume_high"            = 4
   "theme.anemofilia.volume_peak"            = 15
   "theme.anemofilia.volume_indicator"       = 15
   "theme.anemofilia.selected"               = 4
   "theme.anemofilia.default"                = 15
   "theme.anemofilia.border"                 = 4
   "theme.anemofilia.dropdown.selected_text" = 0
   "theme.anemofilia.dropdown.selected"      = 4
   "theme.anemofilia.dropdown.unselected"    = 15
# }
# Keybinds {
   "keycode.9"    = "switch"          # tab
   "keycode.13"   = "select"          # enter
   "keycode.27"   = "quit"            # escape
   "keycode.99"   = "dropdown"        # c
   "keycode.113"  = "quit"            # q
   "keycode.109"  = "mute"            # m
   "keycode.100"  = "set_default"     # d
   "keycode.108"  = "volume_up"       # l
   "keycode.104"  = "volume_down"     # h
   "keycode.261"  = "volume_up"       # arrow right
   "keycode.260"  = "volume_down"     # arrow left
   "keycode.107"  = "move_up"         # k
   "keycode.106"  = "move_down"       # j
   "keycode.259"  = "move_up"         # arrow up
   "keycode.258"  = "move_down"       # arrow down
   "keycode.338"  = "page_up"         # page up
   "keycode.339"  = "page_down"       # page down
   "keycode.76"   = "tab_next"        # L
   "keycode.72"   = "tab_prev"        # H
   "keycode.49"  = "tab_playback"     # 1
   "keycode.50"  = "tab_recording"    # 2
   "keycode.51"  = "tab_output"       # 3
   "keycode.52"  = "tab_input"        # 4
   "keycode.53"  = "tab_config"       # 5
   "keycode.f.80" = "tab_playback"    # f1 VT100
   "keycode.f.81" = "tab_recording"   # f2 VT100
   "keycode.f.82" = "tab_output"      # f3 VT100
   "keycode.f.83" = "tab_input"       # f4 VT100
   "keycode.f.84" = "tab_config"      # f5 VT100
   "keycode.71"   = "move_last"       # G
   "keycode.103"  = "move_first"      # g
#   "keycode.48"   = "set_volume_100"  # 0
   "keycode.63"   = "help"            # ?
# }
