# Accounts

[{{{ aerc.primary.email }}}]
source   = imaps://{{{ aerc.primary.user }}}%40{{{ aerc.primary.url }}}@{{{ aerc.primary.url }}}:993
outgoing = smtp://{{{ aerc.primary.user }}}%40{{{ aerc.primary.url }}}@{{{ aerc.primary.url }}}:587
source-cred-cmd = echo "{{{ aerc.primary.password }}}"
outgoing-cred-cmd = echo "{{{ aerc.primary.password }}}"
default  = INBOX
from     = {{{ aerc.primary.name }}} <{{{ aerc.primary.email }}}>
copy-to  = Sent
check-mail = 2m

[{{{ aerc.secondary.email }}}]
source   = imaps://{{{ aerc.secondary.user }}}%40{{{ aerc.secondary.url }}}@{{{ aerc.secondary.url }}}:993
outgoing = smtp://{{{ aerc.secondary.user }}}%40{{{ aerc.secondary.url }}}@{{{ aerc.secondary.url }}}:587
source-cred-cmd = echo "{{{ aerc.secondary.password }}}"
outgoing-cred-cmd = echo "{{{ aerc.secondary.password }}}"
default  = INBOX
from     = {{{ aerc.secondary.name }}} <{{{ aerc.secondary.email }}}>
copy-to  = Sent
check-mail = 2m
