# See the mpd.conf man page for a more detailed description of each parameter.
music_directory         "~/Music"
playlist_directory      "~/.config/mpd/playlists"
db_file                 "~/.local/state/mpd/database"
log_file                "~/.local/state/mpd/log"
pid_file                "~/.local/state/mpd/pid"
state_file              "~/.local/state/mpd/state"
sticker_file            "~/.local/state/mpd/sticker.sql"

bind_to_address         "any"
port                    "6600"
metadata_to_use         "artist,album,title,track,name,genre,date,composer,performer,disc,comment"
auto_update             "yes"

zeroconf_enabled        "yes"
#zeroconf_name          "Music Player"
# input {
#         plugin          "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
# }
# Audio Output ################################################################
#
audio_output {
        type            "pipewire"
        name            "pw-mpd"
}

audio_output {
             type       "httpd"
             port       "4577"
             name       "http"
             encoder    "flac"
}

#filesystem_charset             "UTF-8"
