flush ruleset

# basic workstation firewall
table inet filter {
    chain input {
        # default drop all
        type filter hook input priority 0; policy drop;
        
        # if interface loopback accept from 127.0.0.0/8 or the ipv6 equivalent
        iif lo accept
        iif != lo ip daddr 127.0.0.0/8 drop
        iif != lo ip6 daddr ::1/128 drop

        # accept traffic that originated from us
        ct state established,related accept

        # accept neighbor discovery for ipv6 and all icmp in v4
        icmpv6 type {nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert} accept
        ip protocol icmp accept
        # allow ssh via port 22
        tcp dport ssh accept
        # neverwinter nights
        udp dport 5121 accept
    }
}
