require("variables")

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("qs")
    hl.exec_cmd("light -S 15")
    hl.exec_cmd("ydotoold")
    hl.exec_cmd("fcitx5 --disable=all --enable=wayland,waylandim,keyboard -d")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd(term .. " --initial-window=false")
    hl.exec_cmd(term .. " --class=com.mail.aerc -e aerc")
    hl.exec_cmd(term .. " --class=com.irc.senpai -e senpai libera")
    hl.exec_cmd(term .. " --class=com.rss.newsraft -e newsraft")
    hl.exec_cmd("fish -c 'test (hostname) = \"yumiko\"; and Telegram'")
    hl.exec_cmd("fish -c 'test (hostname) = \"yumiko\"; and fluxer-canary'")
    hl.exec_cmd("fish -c 'test (hostname) = \"yumiko\"; and steam'")
    hl.exec_cmd("guix shell glib:bin -- gsettings set org.gnome.desktop.interface cursor-theme 'McMojave'")
    hl.exec_cmd("guix shell glib:bin -- gsettings set org.gnome.desktop.interface cursor-size 16")
end)

