exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = waybar

exec-once = hyprpaper

exec-once = hypridle

exec-once = light -S 15

# exec-once = wlsunset -t 4000 -T 6500 -S 06:30 -s 18:00

exec-once = mako

exec-once = ydotoold

# exec-once = ~/.config/hypr/scripts/socket_handler.sh

# exec-once = wayneko --follow-pointer false --layer overlay

exec-once = ghostty --initial-window=false

exec-once = $term --class=com.mail.aerc -e aerc

exec-once = $term --class=com.irc.senpai -e senpai libera

exec-once = $term --class=com.rss.newsraft -e newsraft

exec-once = fish -c 'test (hostname) = "yumiko"; and Telegram'

exec-once = fish -c 'test (hostname) = "yumiko"; and vesktop'

# exec-once = spotify

exec-once = fish -c 'test (hostname) = "yumiko"; and steam'

exec-once = guix shell glib:bin -- gsettings set org.gnome.desktop.interface cursor-theme 'McMojave'

exec-once = guix shell glib:bin -- gsettings set org.gnome.desktop.interface cursor-size 16
