preload = ~/images/backgrounds/flower-branch.png
preload = ~/images/backgrounds/sebastien-gabriel-232361.jpg
preload = ~/images/backgrounds/tree-optimism.png

wallpaper = eDP-1, ~/images/backgrounds/tree-optimism.png
wallpaper = DP-1, ~/images/backgrounds/tree-optimism.png
wallpaper = HDMI-A-1, ~/images/backgrounds/tree-optimism.png

splash = false

ipc = on
