wallpaper {
    monitor = eDP-1
    path = ~/images/backgrounds/tree-optimism.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-1
    path = ~/images/backgrounds/tree-optimism.png
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/images/backgrounds/tree-optimism.png
    fit_mode = fill
}

splash = false

ipc = on
