# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors

monitorv2 {
  output = DP-1
  mode = 1920x1080@143.85
  position = 1920x0
  scale = 1
  transform = 0
  vrr = 1
}

monitorv2{
  output = eDP-1
  mode = 1920x1080@60
  position = 0x0
  scale = 1
  transform = 0
  vrr = 1
}

monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@74.97
  position = 0x0
  scale = 1
  transform = 0
  vrr = 1
}
