# https://wiki.hyprland.org/Configuring/Window-Rules/

# Supported window rules are:
# class - class regex 
# title - title regex
# initialClass - initialClass regex
# initialTitle - initialTitle regex
# xwayland - 0/1
# floating - 0/1
# fullscreen - 0/1
# pinned - 0/1
# focus - 0/1
# workspace - id or name: and name
# onworkspace (how many windows are on the workspace) - int 

layerrule = noscreenshare, notifications

# Add to tag
windowrule = tag +game, class:^(pathofexilesteam.exe|phasmophobia.exe|pioneergame.exe|steam_app_.*|conhost.exe)$
windowrule = tag +browser, class:(chromium-browser|zen)
windowrule = tag +telegram, class:(org.telegram), initialTitle:^(Telegram)$
windowrule = tag +telegram-viewer, class:(org.telegram), initialTitle:^(Telegram)$
windowrule = tag +steam, class:^(steam)$
windowrule = tag +aerc, class:^(com.mail.aerc)$
windowrule = tag +senpai, class:^(com.irc.senpai)$
windowrule = tag +newsraft, class:^(com.rss.newsraft)$
windowrule = tag +spotify, class:^(spotify)$
windowrule = tag +vesktop, initialClass:^(vesktop)$

windowrule = tag +float, class:^(conhost.exe)$
windowrule = tag +float, title: ^()$, class:^(steam)$
windowrule = tag +noscreenshare, class:^(org.telegram|vesktop)$
windowrule = tag +noscreenshare, title:(.*WhatsApp.*), class:(zen)
windowrule = tag +nofancy, class:^(chromium-browser|zen|org.pwmt.zathura|mpv|steam_app_.*|vesktop|com.obsproject.Studio|.*.exe|obsidian|sioyek)$
windowrule = tag +nofancy, initialTitle:^(Minecraft.*)$

# Tag tags
windowrule = tag +nofancy, tag:telegram
windowrule = tag +float, tag:telegram
windowrule = tag +nofancy, tag:game

# Tag rules
windowrule = content game, tag:game
windowrule = tile, tag:steam
windowrule = float, tag:float
windowrule = noscreenshare, tag:noscreenshare
windowrule = opaque, tag:nofancy
windowrule = noblur, tag:nofancy
windowrule = noanim, tag:nofancy
windowrule = size 25% 80%, tag:telegram
windowrule = move 60% 5%, tag:telegram
windowrule = opacity 0.95 override 0.8 override, tag:telegram

# Specific workspace tags
windowrule = workspace 8 silent, tag:game
windowrule = workspace 2 silent, tag:browser

# Specific workspace apps
windowrule = workspace special:telegram silent, tag:telegram
windowrule = workspace special:aerc silent, tag:aerc
windowrule = workspace special:senpai silent, tag:senpai
windowrule = workspace special:newsraft silent, tag:newsraft
windowrule = workspace name:spotify silent, tag:spotify
windowrule = workspace name:vesktop silent, tag:vesktop
windowrule = workspace name:steam silent, tag:steam

# Specific monitors workspaces
# workspace = 1, monitor:DP-1,default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 8, monitor:DP-1, default:false
workspace = 9, monitor:HDMI-A-1, default:false
workspace = 10, monitor:HDMI-A-1, default:false
workspace = name:spotify, monitor:HDMI-A-1, default:false
workspace = name:vesktop, monitor:HDMI-A-1, default:false
workspace = name:steam, monitor:HDMI-A-1, default:false

windowrule=tag +apt, class:^(awakened-poe-trade)$
windowrule=float, tag:apt
windowrule=noblur, tag:apt
windowrule=nofocus, tag:apt
windowrule=noshadow, tag:apt
windowrule=noborder, tag:apt
windowrule=pin, tag:apt 
windowrule=renderunfocused, tag:apt
windowrule=size 100% 100%, tag:apt
windowrule=center, tag:apt
windowrule=fullscreen, class:^(steam_app_238960)$
