# https://wiki.hyprland.org/Configuring/Window-Rules/

# Supported window rules are:
# class - class regex 
# title - title regex
# initialClass - initialClass regex
# initialTitle - initialTitle regex
# xwayland - 0/1
# floating - 0/1
# fullscreen - 0/1
# pinned - 0/1
# focus - 0/1
# workspace - id or name: and name
# onworkspace (how many windows are on the workspace) - int 

# Telegram
windowrulev2 = float, class:(org.telegram), initialTitle:^(Telegram)$
windowrulev2 = size 25% 80%, class:(org.telegram), initialTitle:^(Telegram)$
windowrulev2 = move 60% 5%, class:(org.telegram), initialTitle:^(Telegram)$
windowrulev2 = opacity 0.95 override 0.8 override, class:(org.telegram), initialTitle:^(Telegram)$
windowrulev2 = noanim, class:(org.telegram), initialTitle:^(Telegram)$

# Disable window pretty effects on applications
windowrulev2 = opaque, class:(chromium-browser|zen|org.pwmt.zathura|mpv|steam_app_.*|vesktop|com.obsproject.Studio|.*.exe|obsidian|sioyek)
windowrulev2 = noblur, class:(chromium-browser|zen|org.pwmt.zathura|mpv|steam_app_.*|vesktop|com.obsproject.Studio|.*.exe|obsidian|sioyek)
windowrulev2 = opaque, initialTitle:(Minecraft.*)
windowrulev2 = noblur, initialTitle:(Minecraft.*)
windowrulev2 = float, title:(Media viewer), class:(TelegramDesktop)
windowrulev2 = opaque, title:(Media viewer), class:(TelegramDesktop)

windowrulev2 = noscreenshare, title:(.*WhatsApp.*), class:(zen)
windowrulev2 = noscreenshare, class:(vesktop)
windowrulev2 = noscreenshare, class:(org.telegram)

# Tile fix
windowrulev2 = content game, class:(steam_app_.*)
windowrulev2 = content game, class:(pathofexilesteam.exe|phasmophobia.exe)

# Specific workspace apps
windowrulev2 = workspace 2, class:(chromium-browser|zen)
windowrulev2 = workspace 8, initialClass:^(steam_app_.*)$
windowrulev2 = workspace 8 silent, initialClass:^(pathofexilesteam\.exe)$
windowrulev2 = workspace 7 silent, class:^(path of building\.exe)$

windowrulev2 = workspace special:telegram silent, class:(org.telegram), initialTitle:^(Telegram)$
windowrulev2 = workspace special:aerc silent, class:^(com.mail.aerc)$
windowrulev2 = workspace special:senpai silent, class:^(com.irc.senpai)$
windowrulev2 = workspace special:newsraft silent, class:^(com.rss.newsraft)$
windowrulev2 = workspace name:spotify silent, class:^(spotify)$
windowrulev2 = workspace name:vesktop silent, initialClass:^(vesktop)$
windowrulev2 = workspace name:steam silent, initialClass:^(steam)$

# Specific monitors workspaces
# workspace = 1, monitor:DP-1,default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 8, monitor:DP-1, default:false
workspace = 9, monitor:HDMI-A-1, default:false
workspace = 10, monitor:HDMI-A-1, default:false
workspace = name:spotify, monitor:HDMI-A-1, default:false
workspace = name:vesktop, monitor:HDMI-A-1, default:false
workspace = name:steam, monitor:HDMI-A-1, default:false
