# https://wiki.hyprland.org/Configuring/Window-Rules/

# Supported window rules are:
# class - class regex 
# title - title regex
# initialClass - initialClass regex
# initialTitle - initialTitle regex
# xwayland - 0/1
# floating - 0/1
# fullscreen - 0/1
# pinned - 0/1
# focus - 0/1
# workspace - id or name: and name
# onworkspace (how many windows are on the workspace) - int 

# Workspaces
# workspace = 1, monitor:DP-1,default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 8, monitor:DP-1, default:false
workspace = 9, monitor:HDMI-A-1, default:false
workspace = 10, monitor:HDMI-A-1, default:false
workspace = name:spotify, monitor:HDMI-A-1, default:false
workspace = name:vesktop, monitor:HDMI-A-1, default:false
workspace = name:steam, monitor:HDMI-A-1, default:false

layerrule = no_screen_share 1, match:namespace notifications

windowrule {
    name = telegram

    match:class = ^(org.telegram.desktop)$
    match:initial_title = ^(Telegram)$

    workspace = special:telegram silent

    tag = nofancy

    float = 1
    no_screen_share = 1
    size = (monitor_w*0.25) (monitor_h*0.8)
    move = (monitor_w*0.6) (monitor_h*0.05)
    opacity = 0.95 override 0.8 override
}

windowrule {
    name = telegram-viewer

    match:class = ^(org.telegram.desktop)$
    match:initial_title = ^(Media viewer)$

    workspace = special:telegram silent

    tag = nofancy

    size = (monitor_w*0.5) (monitor_h*0.8)
    move = (monitor_w*0.05) (monitor_h*0.05)
    float            = 1
    no_screen_share  = 1
    suppress_event   = 1
    fullscreen_state = 0 0
}

windowrule {
    name = steam

    match:class = ^(steam)$

    workspace = name:steam silent

    tile = 1
}
windowrule = float 1, match:title ^()$, match:class ^(steam)$
windowrule = float 1, match:title ^(Sign in to Steam)$, match:class ^(steam)$

windowrule {
    name = vesktop

    match:class = ^(vesktop)$

    workspace = name:vesktop silent

    tag = nofancy

    no_screen_share = 1
}

windowrule {
    name = cinny

    match:class = ^(cinny)$

    workspace = name:vesktop silent

    no_screen_share = 1
}

windowrule {
    name = spotify

    match:class = ^(spotify)$

    workspace = name:spotify silent
}

windowrule {
    name = aerc

    match:class = ^(com.mail.aerc)$

    workspace = special:aerc silent
}

windowrule {
    name = senpai

    match:class = ^(com.irc.senpai)$

    workspace = special:senpai silent
}

windowrule {
    name = newsraft

    match:class = ^(com.rss.newsraft)$

    workspace = special:newsraft silent
}

windowrule {
    name = browser

    match:class = ^(zen|chromium-browser)$

    workspace = 2 silent

    tag = nofancy
}

windowrule {
    name = game

    match:class = ^(.*\.exe|steam_app_.*|Minecraft.*)$

    workspace = 8 silent

    tag = nofancy

    content = game

    fullscreen = 1
}

windowrule {
    name = game-fixes

    match:class = ^(conhost\.exe)$

    workspace = 8 silent

    tag = nofancy

    content = game

    float = 1
}

windowrule {
    name = whatsapp

    match:title = (.*WhatsApp.*)
    match:class = ^(zen)$

    no_screen_share = 1
}

windowrule {
    name = pdf

    match:class = ^(org.pwmt.zathura|sioyek)$

    tag = nofancy

    no_screen_share = 1

    content = image
}

windowrule {
    name = media

    match:class = ^(mpv|com.obsproject.Studio)$

    tag = nofancy

    content = video
}

windowrule {
    name = awakened-poe-trade

    match:class = ^(awakened-poe-trade)$

    size = (monitor_w) (monitor_h)
    float            = 1
    no_blur          = 1
    no_focus         = 1
    no_shadow        = 1
    pin              = 1
    render_unfocused = 1
    center           = 1
    fullscreen       = 1
}

windowrule {
    name = nofancy

    match:tag = nofancy

    opaque    = 1
    no_blur   = 1
    no_anim   = 1
    no_shadow = 1
}
