# -*- conf -*-

# For documentation on these options, see `man fnott.ini`
# Global values
# output=<undefined>#
# min-width=0
max-width=500
# max-height=0
# stacking-order=bottom-up
anchor=top-right
edge-margin-vertical=20
edge-margin-horizontal=20
# notification-margin=10
# icon-theme=hicolor
# max-icon-size=32
# selection-helper=dmenu
# play-sound=aplay ${filename}
# layer=top

# Default values, may be overridden in 'urgency' specific sections
background=222524EE

# border-color=909090ff
# border-size=1

# padding-vertical=20
# padding-horizontal=20

# dpi-aware=auto

title-font=DejaVu Sans Mono:size=20
title-color=ffa21fFF
title-format=<b>%s\n</b>
# title-format=<b>%a%A</b>

summary-font=DejaVu Sans Mono:size=16
summary-color=eaf2efFF
summary-format=%b\n
# summary-format=%s\n

# body-font=sans serif
# body-color=7fbbb3FF
body-format=
# body-format=%b\n

# progress-bar-height=20
# progress-bar-color=ffffffff

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
default-timeout=5
# idle-timeout=0

# [low]
# background=2b2b2bff
# title-color=888888ff
# summary-color=888888ff
# body-color=888888ff

# [normal]

# [critical]
# background=6c3333ff
