[window]
opacity = 0.8
padding.x = 20
padding.y = 20

[font]
normal.family = "DejaVu Sans Mono"
size = 12

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = "#0f0e06"
# soft contrast background = = '#32302f'
foreground = "#cfbcba"

# Normal colors
[colors.normal]
black   = "#000000"
red     = "#ff7a7f"
green   = "#2fa526"
yellow  = "#c48702"
blue    = "#6a88ff"
magenta = "#d570af"
cyan    = "#4fb0cf"
white   = "#a6a6a6"

# Bright colors
[colors.bright]
black   = '#595959'
red     = "#f06a3f"
green   = "#64aa0f"
yellow  = "#d0730f"
blue    = "#029fff"
magenta = "#af8aff"
cyan    = "#6fafff"
white   = "#ffffff"
