[window]
opacity = 0.8
padding.x = 20
padding.y = 20

[font]
normal.family = "DejaVu Sans Mono"
size = 13

# Default colors
[colors.primary]
background = "#352718"
foreground = "#e8e4b1"

# Normal colors
[colors.normal]
black   = "#000000"
red     = "#ff7f7f"
green   = "#6fd560"
yellow  = "#e4b53f"
blue    = "#57aff6"
magenta = "#f0aac5"
cyan    = "#6fcad0"
white   = "#a6a6a6"

# Bright colors
[colors.bright]
black   = '#595959'
red     = "#ff7f4f"
green   = "#65d590"
yellow  = "#ffa21f"
blue    = "#62cfef"
magenta = "#fa90aa"
cyan    = "#70e0cf"
white   = "#ffffff"
