[window]
opacity = 0.8
padding.x = 20
padding.y = 20

[font]
normal.family = "DejaVu Sans Mono"
size = 13

# Default colors
[colors.primary]
background = "#222524"
foreground = "#eaf2ef"

# Normal colors
[colors.normal]
black   = "#000000"
red     = "#ff656a"
green   = "#7fc87f"
yellow  = "#cac85f"
blue    = "#57aff6"
magenta = "#f59acf"
cyan    = "#7fcfdf"
white   = "#a6a6a6"

# Bright colors
[colors.bright]
black   = '#595959'
red     = "#ff7a5f"
green   = "#50cf89"
yellow  = "#e0b02f"
blue    = "#78afff"
magenta = "#cfaaff"
cyan    = "#60d5c2"
white   = "#ffffff"
