;;; init.el --- Custom editor configuration for SSS -*- lexical-binding: t -*-

;; Copyright (C) 2025 Josep Bigorra

;; Author: Josep Bigorra <jjbigorra@gmail.com>
;; Maintainer: Josep Bigorra <jjbigorra@gmail.com>
;; URL: https://codeberg.org/jjba23/sss

;; sss is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; sss is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with sss.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This Emacs configuration was last tested to work properly with:
;;   - GNU Emacs 30.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)

;;; Code:

;; ====== Package manager ======

;; Install the Elpaca package manager
(defvar elpaca-installer-version 0.10)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1 :inherit ignore
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (<= emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                  ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                  ,@(when-let* ((depth (plist-get order :depth)))
                                                      (list (format "--depth=%d" depth) "--no-single-branch"))
                                                  ,(plist-get order :repo) ,repo))))
                  ((zerop (call-process "git" nil buffer t "checkout"
                                        (or (plist-get order :ref) "--"))))
                  (emacs (concat invocation-directory invocation-name))
                  ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                        "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                  ((require 'elpaca))
                  ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Enable integration of use-package with Elpaca
(elpaca elpaca-use-package (elpaca-use-package-mode))

;; ====== Configuration ======

;; Add user Emacs Lisp modules
(defconst user-init-dir
  (cond ((boundp 'user-emacs-directory)
         user-emacs-directory)
        ((boundp 'user-init-directory)
         user-init-directory)
        (t "~/.emacs.d/")))

(defun load-user-file (file)
  (interactive "f")
  "Load a file in current user's configuration directory, often ~/.emacs.d, ignoring errors for resilience"
  (if (file-exists-p (expand-file-name file user-init-dir))
      (progn
	(ignore-errors
	  (load-file (expand-file-name file user-init-dir))))
    (message (format "file doesn't exist: %s" (expand-file-name file user-init-dir)))))

;; ====== Load user modules ======

(load-user-file "modules/sss.el")

;; Load the bridge between SSS (Supreme Sexp System) and Emacs
;; factually binding Guile Scheme + Guix and Emacs together
;; this file should be auto-generated by SSS
(load-user-file "sss-bridge.el")

;; Load more user modules
(load-user-file "modules/dashboard.el")
(load-user-file "modules/common-lisp.el")
(load-user-file "modules/go.el")
(load-user-file "modules/org.el")
(load-user-file "modules/theme.el")
(load-user-file "modules/emacs-core.el")
(load-user-file "modules/erc.el")
(load-user-file "modules/consult.el")
(load-user-file "modules/eglot.el")
(load-user-file "modules/dev.el")


(use-package git-riddance 
  :ensure (:host codeberg :repo "jjba23/git-riddance.el" :branch "trunk"))

(use-package modusregel
  :ensure (:host codeberg :repo "jjba23/modusregel" :branch "trunk")
  :demand t
  :after (keycast)
  :config
  (add-to-list 'modusregel-format '("" keycast-mode-line) t)
  (setq-default mode-line-format modusregel-format))

(use-package dagboek
  :ensure (:host codeberg :repo "jjba23/dagboek.el" :branch "trunk")
  :bind (("C-c ; v" . dagboek-today-entry)
         ("C-c ; g" . dagboek-yesterday-entry)))

(use-package keycast
  :ensure t
  :demand t
  :after (tekengrootte)
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
	(add-hook 'pre-command-hook 'keycast--update t)
      (remove-hook 'pre-command-hook 'keycast--update)))
  (ignore-errors (keycast-mode)))


(use-package tekengrootte 
  :ensure (:host codeberg :repo "jjba23/tekengrootte.el" :branch "trunk")
  :demand t
  :bind (("C-c f c" . tekengrootte-set-scale-colossal) 
         ("C-c f j" . tekengrootte-set-scale-jumbo) 
         ("C-c f x" . tekengrootte-set-scale-larger) 
         ("C-c f l" . tekengrootte-set-scale-large) 
         ("C-c f r" . tekengrootte-set-scale-regular) 
         ("C-c f s" . tekengrootte-set-scale-small) 
         ("C-c f t" . tekengrootte-set-scale-tiny)
	 ("C-c f n" . tekengrootte-set-scale-nano)) 
  :hook ((tekengrootte-set-scale . (lambda () 
                                     (sss-set-base-faces)))) 
  :after (ef-themes solarized-theme)
  :config
  (defun sss-set-base-faces ()
    "Adjust the base Emacs faces to my preferences.
According to size, color and font family"
    (interactive)

    (set-face-attribute 'window-divider nil
                        :foreground (ef-themes-get-color-value 'bg-alt)
                        :background (ef-themes-get-color-value 'bg-alt))
    (set-face-attribute 'default nil 
		        :height (round (tekengrootte-mk-font-size 114)) 
		        :font sss-font-mono)
    (set-face-attribute 'mode-line nil 
		        :height (tekengrootte-mk-font-size 0.7)
		        :font sss-font-mono) 
    (set-face-attribute 'mode-line-active nil 
		        :height (tekengrootte-mk-font-size 0.7) 
		        :font sss-font-mono) 
    (set-face-attribute 'mode-line-inactive nil 
		        :height (tekengrootte-mk-font-size 0.7) 
		        :font sss-font-mono)
    (set-face-attribute 'variable-pitch nil 
		        :font sss-font-sans
                        :height (tekengrootte-mk-font-size 1.05))

    (set-face-attribute 'org-default nil 
		        :height (tekengrootte-mk-font-size 1.05)
		        :font sss-font-mono)
    (set-face-attribute 'button nil :background 'unspecified
                        :weight 'bold)
    (set-face-attribute 'org-block nil
		        :font sss-font-mono
                        :height (tekengrootte-mk-font-size 1.05))
    (set-face-attribute 'font-lock-doc-face nil
                        :foreground (ef-themes-get-color-value 'yellow-faint))
    (set-face-attribute 'org-code nil                       
		        :font sss-font-mono
                        :height (tekengrootte-mk-font-size 1.05))
    (set-face-attribute 'org-verbatim nil                       
		        :font sss-font-mono
                        :height (tekengrootte-mk-font-size 1.05))
    (set-face-attribute 'org-document-title nil 
		        :height (tekengrootte-mk-font-size 1.2))
    (set-face-attribute 'org-level-1 nil
                        :font sss-font-sans
		        :height (tekengrootte-mk-font-size 1.2))
    (set-face-attribute 'org-level-2 nil
                        :font sss-font-sans
		        :height (tekengrootte-mk-font-size 1.2))
    (set-face-attribute 'org-level-3 nil
                        :font sss-font-sans
		        :height (tekengrootte-mk-font-size 1.1))
    (set-face-attribute 'org-level-4 nil
                        :font sss-font-sans
		        :height (tekengrootte-mk-font-size 1.1))
    (set-face-attribute 'org-level-5 nil
                        :font sss-font-sans
		        :height (tekengrootte-mk-font-size 1.0))
    (ignore-errors
      (set-face-attribute 'keycast-key nil                       
		          :font sss-font-mono
                          :background 'unspecified
                          :box nil
                          :height (tekengrootte-mk-font-size 0.9)))
    (ignore-errors
      (set-face-attribute 'keycast-command nil                       
		          :font sss-font-mono
                          :height (tekengrootte-mk-font-size 0.8)))

    ;; ====== Theme specific tweaks ======
    ;; ====== Everforest dark specific tweaks ======
    (ignore-errors
      (cond ((equal sss-emacs-theme 'everforest-hard-dark)
             (progn
               (set-face-attribute 'mode-line nil
                                   :box 'unspecified
                                   :foreground "#2b3339"
                                   :background "#96b070")
               (set-face-attribute 'mode-line-active nil
                                   :box 'unspecified
                                   :foreground "#2b3339"
                                   :background "#96b070")
               (set-face-attribute 'dired-directory nil
                                   :inherit '(font-lock-string-face))))))

    ;; ====== Everforest light specific tweaks ======
    (ignore-errors
      (cond ((equal sss-emacs-theme 'everforest-hard-light)
             (progn
               (set-face-attribute 'mode-line nil
                                   :box 'unspecified
                                   :foreground "#2b3339"
                                   :background "#96b070")
               (set-face-attribute 'mode-line-active nil
                                   :box 'unspecified
                                   :foreground "#2b3339"
                                   :background "#96b070")
               (set-face-attribute 'dired-directory nil
                                   :inherit '(font-lock-string-face))))))


    ;; ====== Final tweaks ======
    (ignore-errors
      (set-face-attribute 'mode-line-active nil
                          :box `(:line-width 3 :color ,(face-attribute 'mode-line-active :background))))
    (ignore-errors
      (set-face-attribute 'mode-line-inactive nil
                          :box `(:line-width 3 :color ,(face-attribute 'mode-line-inactive :background))))
    )
  
  (sss-set-base-faces))


(use-package markdown-mode 
  :ensure t 
  :mode "\\.md\\'"
  :hook ((markdown-mode . sss-markdown-mode))
  :config
  (defun sss-markdown-mode ()
    (variable-pitch-mode 0)
    (auto-fill-mode 0)
    (visual-line-mode 1)
    (set-face-attribute 'markdown-code-face nil                       
		        :font sss-font-mono
                        :height (tekengrootte-mk-font-size 1.05))
    (set-face-attribute 'markdown-pre-face nil                       
		        :font sss-font-mono
                        :height (tekengrootte-mk-font-size 1.15))
    ))


(use-package compat
  :ensure (:host github :repo "emacs-compat/compat" :branch "main"))



(use-package vertico 
  :ensure t 
  :init
  (setq vertico-cycle t
        vertico-resize t)
  :config
  (require 'vertico-multiform)
  (add-to-list 'vertico-multiform-categories
               '(jinx grid (vertico-grid-annotate . 20)))
  (vertico-mode)
  (vertico-multiform-mode 1))

(use-package marginalia 
  :ensure t 
  :after (vertico) 
  :config (marginalia-mode))

(use-package nerd-icons :ensure t)

(use-package nerd-icons-completion 
  :ensure t  
  :after (nerd-icons marginalia) 
  :hook ((marginalia-mode . nerd-icons-completion-marginalia-setup)) 
  :config (nerd-icons-completion-mode))

(use-package flymake-collection 
  :ensure t 
  :hook ((after-init . flymake-collection-hook-setup) 
         (emacs-lisp-mode . flymake-mode)))

(use-package transient :ensure t)

(use-package magit :ensure t :after (transient))

(use-package ripgrep
  :ensure t
  :bind (("C-c z r" . ripgrep-regexp)))


(use-package tempel
  :ensure (:host github :repo "minad/tempel" :branch "main")
  :custom
  (tempel-trigger-prefix "<")

  :bind (("M-+" . tempel-complete) ;; Alternative tempel-expand
         ("M-*" . tempel-insert))
  :init
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand
                      completion-at-point-functions)))

  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf))


(use-package gptel
  :ensure t
  :after (f)
  :config
  (setq
   gptel-model 'gemini-pro
   gptel-backend (gptel-make-gemini "Gemini"
                   :key (lambda() (f-read-text "~/.secrets/gemini"))
                   :stream t)))

(use-package super-save 
  :ensure t  
  :init (setq super-save-auto-save-when-idle t auto-save-default nil make-backup-files nil) 
  :config (super-save-mode +1) 
  (add-to-list 'super-save-hook-triggers 'find-file-hook))

(use-package spacious-padding 
  :ensure (:host github :repo "protesilaos/spacious-padding" :branch "main")
  :init
  (setq spacious-padding-widths
        '( :internal-border-width 18 
           :header-line-width 2 
           :mode-line-width 2 
           :tab-width 4 
           :right-divider-width 2 
           :scroll-bar-width 8 
           :left-fringe-width 16 
           :right-fringe-width 16)) 
  (setq spacious-padding-subtle-mode-line nil) 
  :config
  (spacious-padding-mode))

(use-package rainbow-mode
  :ensure (:host github :repo "emacsmirror/rainbow-mode" :branch "master"))

(use-package ob-http :ensure t)

(use-package ob-mermaid :ensure t)

(use-package mermaid-mode
  :ensure t
  :init
  (setq mermaid-mmdc-location "~/.nix-profile/bin/mmdc")
  :config
  (setq mermaid-mode-map
        (let ((map mermaid-mode-map))
          (define-key map (kbd "C-c C-c") nil)
          (define-key map (kbd "C-c C-f") nil)
          (define-key map (kbd "C-c C-b") nil)
          (define-key map (kbd "C-c C-r") nil)
          (define-key map (kbd "C-c C-o") nil)
          (define-key map (kbd "C-c C-d") nil)
          (define-key map (kbd "C-c C-d c") 'mermaid-compile)
          (define-key map (kbd "C-c C-d c") 'mermaid-compile)
          (define-key map (kbd "C-c C-d f") 'mermaid-compile-file)
          (define-key map (kbd "C-c C-d b") 'mermaid-compile-buffer)
          (define-key map (kbd "C-c C-d r") 'mermaid-compile-region)
          (define-key map (kbd "C-c C-d o") 'mermaid-open-browser)
          (define-key map (kbd "C-c C-d d") 'mermaid-open-doc)
          map)))

(use-package page-break-lines :ensure t)

(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))

(use-package f :ensure t)

(use-package speed-type :ensure t)

;; TODO work on debugger support (use GUD? Realgud? DAPE?)
;; (use-package dape 
;;   :ensure t  
;;   :init (setq dape-buffer-window-arrangement 'gud))

(use-package dired-hacks-utils :ensure t)

(use-package dired-subtree 
  :ensure t
  :config
  (set-face-attribute 'dired-subtree-depth-1-face nil                       
		      :background 'unspecified)
  (set-face-attribute 'dired-subtree-depth-2-face nil                       
		      :background 'unspecified)
  (set-face-attribute 'dired-subtree-depth-3-face nil                       
		      :background 'unspecified)
  (set-face-attribute 'dired-subtree-depth-4-face nil                       
		      :background 'unspecified)
  (set-face-attribute 'dired-subtree-depth-5-face nil                       
		      :background 'unspecified)
  (set-face-attribute 'dired-subtree-depth-6-face nil
		      :background 'unspecified)
  :bind (:map dired-mode-map (("<mouse-1>" . dired-subtree-toggle)
                              ("<TAB>" . dired-subtree-toggle) 
                              ("C-<tab>" . dired-subtree-toggle) 
                              ("C-<TAB>" . dired-subtree-toggle))))

(use-package dired-open-with :ensure t)

(use-package move-text 
  :ensure t  
  :config (move-text-default-bindings))

(use-package ultra-scroll
  :ensure (:host github :repo "jdtsmith/ultra-scroll" :branch "main")
  :init
  (setq scroll-conservatively 101 ; important!
        scroll-margin 0) 
  :config
  (ultra-scroll-mode 1))

(use-package corfu
  :ensure t 
  :init
  (setq corfu-cycle t
        corfu-auto t
        corfu-auto-prefix 2
        corfu-auto-delay 0.2
        corfu-quit-at-boundary 'separator
        corfu-quit-no-match 'separator
        corfu-echo-documentation 0.25
        corfu-preview-current 'insert
        corfu-preselect-first nil
        corfu-popupinfo-delay '(0.8 . 0.8))
  :config
  (global-corfu-mode)
  (corfu-history-mode)
  (corfu-popupinfo-mode 1))

(use-package svg-lib
  :ensure (:host github :repo "rougier/svg-lib" :branch "master"))

(use-package kind-icon
  :ensure (:host github :repo "jdtsmith/kind-icon" :branch "main")
  :after corfu
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

(use-package guix
  :ensure t)


(use-package pandoc-mode :ensure t)

(use-package nerd-icons-dired 
  :ensure t  
  :hook ((dired-mode . nerd-icons-dired-mode)))

(use-package queue
  :ensure (:host github :repo "emacs-straight/queue" :branch "master")
  :demand t)


(use-package helpful
  :ensure t
  :bind (
	 ("C-h f" . helpful-callable)
	 ("C-h v" . helpful-variable)
	 ("C-h k" . helpful-key)
	 ("C-c C-d" . helpful-at-point)
	 ("C-h F" . helpful-function)
	 ("C-h C" . helpful-command)))

(use-package cape
  :ensure t
  :bind ("C-c p" . cape-prefix-map)
  :init
  ;; first function returning a result wins
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-history)
  (add-hook 'completion-at-point-functions #'cape-elisp-block))

(defun sss-joe-reconfigure ()
  "Rebuild GNU Guix Joe's configs."
  (interactive)
  (let ((default-directory (string-replace "$HOME" "~" sss-clone-dir)))
    (async-shell-command "make jr")))

(defun sss-publish-manual ()
  "Rebuild GNU Guix Joe's config manual."
  (interactive)
  (let ((default-directory (string-replace "$HOME" "~" sss-clone-dir)))
    (async-shell-command "make publish-manual")))

(defun sss-full-reconfigure ()
  "Fully Rebuild GNU Guix Joe's configs and Joe's user."
  (interactive)
  (let ((default-directory (string-replace "$HOME" "~" sss-clone-dir)))
    (async-shell-command "make fr")))

(defun sss-sys-reconfigure ()
  "Rebuild GNU Guix Joe's configs."
  (interactive)
  (let ((default-directory (string-replace "$HOME" "~" sss-clone-dir)))
    (async-shell-command "make sr")))

(defun sss-sys-update ()
  "Update GNU Guix packages."
  (interactive)
  (let ((default-directory (string-replace "$HOME" "~" sss-clone-dir)))
    (async-shell-command "make update")))

(use-package flymake
  :ensure nil
  :bind(("C-c ! b" . flymake-show-buffer-diagnostics)
	("C-c ! n" . flymake-goto-next-error)
	("C-c ! p" . flymake-show-project-diagnostics)
	("C-c ! f" . flymake-mode)))

;; TODO enable jinx
;; (use-package jinx
;;   :ensure (:host github :repo "minad/jinx" :branch "main")
;;   :bind (("M-$" . jinx-correct)
;;          ([remap ispell-word] . #'jinx-correct)
;;          ("C-M-$" . jinx-languages))
;;   :init
;;   (setq jinx-languages "en_US nl_NL")
;;   :config
;;   (dolist (hook '(text-mode-hook
;;                   prog-mode-hook
;;                   conf-mode-hook
;;                   org-mode-hook
;;                   markdown-mode-hook))
;;     (add-hook hook #'jinx-mode)))


;; ====== emacs Multimedia System ======

(use-package emms
  :ensure t
  :init
  (require 'emms-setup)
  (require 'emms-mpris)
  (emms-all)
  (emms-default-players)
  (emms-mpris-enable)
  :custom
  (emms-source-file-default-directory sss-ews-music-directory)
  (emms-browser-covers #'emms-browser-cache-thumbnail-async)
  :bind
  (("<f5>"   . emms-browser)
   ("M-<f5>" . emms)
   ("<XF86AudioPrev>" . emms-previous)
   ("<XF86AudioNext>" . emms-next)
   ("<XF86AudioPlay>" . emms-pause)))

(use-package prodigy
  :ensure t)


;; ====== SSS Emacs-Lisp functions ======

(defun sss-uuidgen ()
  (interactive)
  (let ((uid (string-replace "\n" "" (shell-command-to-string "uuidgen"))))
    (message (format "generated UUID: %s" uid))
    (kill-new uid)
    ))

(defun sss-guix-fmt ()
  (interactive)
  (let ((path (file-truename buffer-file-name)))
    (message "formatting current buffer with Guix style")
    (shell-command (format "guix style -f %s" path))
    (revert-buffer :ignore-auto :noconfirm)
    (message "formatted current buffer with Guix style")
    ))

;;; init.el ends here
