(define-module (misako home-environments look sops)
  #:use-module (sops secrets)
  #:use-module (guix gexp)
  #:use-module (misako utils)
  #:export (all
            all-keys))

(define (look-sops-secret keys)
  (map (lambda (key)
         (sops-secret
           (key key)
           (file (local-file (string-append look-sops-dir "/look.yaml")))
           (permissions #o400)))
       keys))

(define all-keys
  (list '("aerc" "primary"   "name")
        '("aerc" "primary"   "user")
        '("aerc" "primary"   "url")
        '("aerc" "primary"   "email")
        '("aerc" "primary"   "password")
        '("aerc" "secondary" "name")
        '("aerc" "secondary" "user")
        '("aerc" "secondary" "url")
        '("aerc" "secondary" "email")
        '("aerc" "secondary" "password")
        '("senpai" "sourcehut" "password")
        '("irc" "libera" "password")
        '("ssh" "shadow-primary" "name")
        '("ssh" "shadow-primary" "host-name")
        '("ssh" "shadow-primary" "port")
        '("ssh" "shadow-primary" "user")
        '("ssh" "shadow-secondary" "name")
        '("ssh" "shadow-secondary" "host-name")
        '("ssh" "shadow-secondary" "port")
        '("ssh" "shadow-secondary" "user")))

(define all (look-sops-secret all-keys))
