(define-module (misako home-environments look sops)
  #:use-module (sops secrets)
  #:use-module (guix gexp)
  #:use-module (misako utils)
  #:export (all))

(define (look-sops-secret keys)
  (map (lambda (key)
         (sops-secret
           (key key)
           (user "look")
           (group "users")
           (file (local-file (string-append look-sops-dir "/look.yaml")))
           (permissions #o400)))
       keys))

(define-public all-keys
  (list '("aerc" "primary"   "name")
        '("aerc" "primary"   "user")
        '("aerc" "primary"   "url")
        '("aerc" "primary"   "email")
        '("aerc" "primary"   "password")
        '("aerc" "secondary" "name")
        '("aerc" "secondary" "user")
        '("aerc" "secondary" "url")
        '("aerc" "secondary" "email")
        '("aerc" "secondary" "password")
        '("senpai" "sourcehut" "password")
        '("irc" "libera" "password")))

(define all (look-sops-secret all-keys))
