[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.inline-diagnostics]
cursor-line = "warning"

#
# Keybinds
#

[keys.normal]
"A-c" = "@mammammammammammammammammammammammammammammammam"

[keys.normal.g.a]
# compute and replace HASH for PACKAGE where cursor is inside the definition
h = "@mammammammammammammammammammammammammammammammams\\(name<ret>f\";mim\"0ymammammammammammammammammammammammammammammammams\\(base32<ret>f\";mimr0:w!<ret>|guix build -L. <C-r>0<ret>sactual hash: *<ret>lvgl<esc>\"0ymim\"0Rzz:w!<ret>;"
# execute guix build on the current PACKAGE where cursor is inside the definition and display in-line
b = "@mammammammammammammammammammammammammammammammams\\(name<ret>f\";mim\"0y:sh guix build -L. <C-r>0<ret>"
# execute guix build on the current PACKAGE where cursor is inside the definition and display in a new vertical buffer window
B = "@mammammammammammammammammammammammammammammammams\\(name<ret>f\";mim\"0y<space>wnv|guix build -L. <C-r>0<ret>"
