(deftheme meimuna
  "Created 2022-01-11.")

(custom-theme-set-variables
 'meimuna
 '(overline-margin 0))

(custom-theme-set-faces
 'meimuna
 '(eat-term-color-1 ((t (:background "#df6760" :foreground "#df6760"))))
 '(eat-term-color-0 ((t (:background "#000000" :foreground "#000000"))))
 '(eat-term-color-2 ((t (:background "#8be760" :foreground "#8be760"))))
 '(eat-term-color-3 ((t (:background "#ffd17a" :foreground "#ffd17a"))))
 '(eat-term-color-4 ((t (:background "#9688d9" :foreground "#9688d9"))))
 '(eat-term-color-5 ((t (:background "#fc97ff" :foreground "#fc97ff"))))
 '(eat-term-color-6 ((t (:background "#86adff" :foreground "#86adff"))))
 '(eat-term-color-7 ((t (:background "#f1f1f1" :foreground "#f1f1f1"))))
 '(eat-term-color-8 ((t (:background "#808080" :foreground "#808080"))))
 '(eat-term-color-9 ((t (:inherit eat-term-color-1))))
 '(eat-term-color-10 ((t (:inherit eat-term-color-2))))
 '(eat-term-color-11 ((t (:inherit eat-term-color-3))))
 '(eat-term-color-12 ((t (:inherit eat-term-color-4))))
 '(eat-term-color-13 ((t (:inherit eat-term-color-5))))
 '(eat-term-color-14 ((t (:inherit eat-term-color-6))))
 '(eat-term-color-15 ((t (:background "#f1f1f1" :foreground "#f1f1f1"))))
 '(org-document-title ((t (:height 1.2 :underline nil :inherit org-level-1))))
 '(org-level-1 ((t (:inherit default :extend t :foreground "#f6f3e8" :height 1.1 :family "Sans Serif"))))
 '(org-level-2 ((t (:family "Sans Serif" :height 1.0 :foreground "#f6f3e8" :extend t :inherit default))))
 '(org-level-3 ((t (:foreground "#f6f3e8" :extend t :inherit default))))
 '(org-level-4 ((t (:inherit default :extend t :foreground "#f6f3e8"))))
 '(org-level-5 ((t (:inherit default :extend t :foreground "#f6f3e8"))))
 '(org-level-6 ((t (:extend t :foreground "#f6f3e8" :inherit (default)))))
 '(org-level-7 ((t (:extend t :foreground "#f6f3e8" :inherit (default)))))
 '(org-level-8 ((t (:extend t :foreground "#f6f3e8" :inherit (default)))))
 '(org-todo ((t (:foreground "#00ff00" :weight bold))))
 '(org-done ((t (:foreground "#ff0000" :weight bold))))
 '(org-table ((t (:foreground "#999999"))))
 '(org-ellipsis ((t (:foreground "#fff"))))
 '(org-block-begin-line ((t (:background "#606590" :extend t :inherit \#fff))))
 '(org-block-end-line ((t (:inherit \#fff :extend t :background "#606590"))))
 '(org-scheduled ((t (:foreground "#606590" :weight bold))))
 '(org-date ((t (:underline (:color foreground-color :style line) :foreground "#8c86e4"))))
 '(org-tag ((t (:bold t))))
 '(org-warning ((t (:inherit font-lock-warning-face))))
 '(org-headline-todo ((t (:foreground "#fff"))))
 '(org-sexp-date ((t (:foreground "#999999"))))
 '(org-agenda-date ((t (:foreground "#999999"))))
 '(org-date-selected ((t (:foreground "#999999" :inverse-video t))))
 '(org-footnote ((t (:underline (:color foreground-color :style line) :style nil :foreground "#8c86e4"))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date :foreground "#444083" :weight bold))))
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "#444083" :weight bold))))
 '(org-formula ((t (:foreground "khaki"))))
 '(org-scheduled-previously ((t (:foreground "khaki"))))
 '(org-upcoming-deadline ((t (:foreground "khaki" :weight bold))))
 '(org-document-info ((t (:foreground "#fff"))))
 '(org-drawer ((t (:foreground "#999999"))))
 '(org-latex-and-related ((t (:foreground "#fff"))))
 '(org-scheduled-today ((t (:foreground "khaki" :weight ultra-bold))))
 '(org-time-grid ((t (:foreground "#8c86e4"))))
 '(mode-line ((t (:background "#303030" :foreground "#9688d9"))))
 '(mode-line-buffer-id ((t (:weight bold :box nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-inactive ((t (:background "#111111" :foreground "dim gray"))))
 '(cursor ((t (:background "#9688d9" :foreground "#ffffff"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:background "#211d3c" :foreground "khaki"))))
 '(homoglyph ((t (:foreground "khaki"))))
 '(minibuffer-prompt ((t (:foreground "#9688d9"))))
 '(highlight ((t (:background "#9688d9" :foreground "black"))))
 '(region ((t (:extend t :background "#1F102f"))))
 '(shadow ((t (:foreground "#999999"))))
 '(secondary-selection ((t (:extend t :background "#9a9a9a"))))
 '(font-lock-builtin-face ((t (:foreground "#ffd17a"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#86adff"))))
 '(font-lock-comment-face ((t (:foreground "#86adff"))))
 '(font-lock-constant-face ((t (:foreground "#df6760"))))
 '(font-lock-doc-face ((t (:foreground "#9a99e7" :inherit font-lock-string-face))))
 '(font-lock-function-name-face ((t (:foreground "#86adff"))))
 '(font-lock-keyword-face ((t (:foreground "#8681e0"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
 '(font-lock-string-face ((t (:foreground "#fc97ff"))))
 '(font-lock-type-face ((t (:foreground "#ffd17a"))))
 '(font-lock-variable-name-face ((t nil)))
 '(font-lock-warning-face ((t (:foreground "#dce081" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#8c86e4" :underline (:color foreground-color :style line)))))
 '(link-visited ((t (:foreground "#999999" :inherit link))))
 '(fringe ((t (:foreground "#506080" :background "#111111"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:foreground "#FFFFFF" :background "#5f5e8a"))))
 '(isearch ((t (:foreground "white" :background "#5533AA"))))
 '(isearch-fail ((t (:foreground "#999"))))
 '(lazy-highlight ((t (:inherit default :background "#8581e0"))))
 '(match ((t (:background "#9688d9" :foreground "white"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit isearch :background "khaki" :foreground "#101010"))))
 '(line-number-current-line ((t (:inherit line-number :background "#313131" :foreground "#8581e0"))))
 '(line-number ((t (:inherit (shadow default)))))
 '(line-number-major-tick ((((class color grayscale) (background light)) (:bold t :background "grey85")) (((class color grayscale) (background dark)) (:bold t :background "grey75")) (t (:inherit (line-number)))))
 '(whitespace-space ((t (:foreground "#E0E0E0"))))
 '(whitespace-hspace ((t (:inherit whitespace-space))))
 '(whitespace-tab ((t (:inherit whitespace-space))))
 '(whitespace-newline ((t (:inherit whitespace-space))))
 '(whitespace-trailing ((t (:inherit whitespace-space))))
 '(whitespace-space-before-tab ((t (:inherit whitespace-space))))
 '(whitespace-indentation ((t (:inherit whitespace-space))))
 '(whitespace-big-indent ((t (:inherit whitespace-space))))
 '(whitespace-empty ((t (:extend t :inherit whitespace-space))))
 '(whitespace-space-after-tab ((t (:inherit whitespace-space))))
 '(whitespace-missing-newline-at-eof ((t (:inherit whitespace-space))))
 '(whitespace-line ((t nil)))
 '(trailing-whitespace ((t (:inherit whitespace-space))))
 '(fill-column-indicator ((t (:foreground "#303030" :background "#303030"))))
 '(hl-fill-column-face ((t (:background "#303030"))))
 '(hl-line ((t (:inherit fill-column-indicator))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "#a790d3"))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground "#6cdae0"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#ff7f50"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "#ffea8c"))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#83dcaf"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#eba4d4"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#8b5be7"))))
 '(rainbow-delimiters-unmatched-face ((t (:inherit default))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit default))))
 '(rainbow-delimiters-base-error-face ((default (:inherit (rainbow-delimiters-base-face))) (t (:foreground "#88090B"))))
 '(eros-result-overlay-face ((t (:foreground "#808080"))))
 '(geiser-font-lock-repl-output ((t (:foreground "#d0d0d0"))))
 '(corfu-current ((t (:background "#9688d9" :foreground "white"))))
 '(show-paren-match ((t (:overline t :weight ultra-heavy :width extra-expanded))))
 '(orderless-match-face-0 ((t (:weight bold))))
 '(orderless-match-face-1 ((t (:inherit orderless-match-face-0))))
 '(orderless-match-face-2 ((t (:inherit orderless-match-face-0))))
 '(orderless-match-face-3 ((t (:inherit orderless-match-face-0))))
 '(vertico-current ((t (:extend t :inherit (highlight)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#101010" :foreground "#f0f0f0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :foundry "PfEd" :family "Monospace")))))

(provide-theme 'meimuna)
