;; base colors
(defvar red     "#df6760")
(defvar green   "#8be760")
(defvar yellow  "#ffd17a")
(defvar blue    "#9688d9")
(defvar magenta "#fc97ff")
(defvar cyan    "#86adff")
(defvar white   "#dddddd")
(defvar gray    "#808080")
(defvar dark-gray "#313131")
(defvar darker-gray "#1a1a1a")
(defvar black   "#000000")

;; normal and focused colors
(defvar normal-bg darker-gray)
(defvar normal-fg white)

(defvar focused-bg dark-gray)
(defvar focused-fg blue)

(deftheme anemofilia
  "Created 2022-01-11.")

(defface tab-bar-tab-focused-occupied
  `((t :inherit tab-bar-tab :overline t))
    "Tab bar face for focused tabs that are occupied."
   :group 'tab-bar-faces)
(defface tab-bar-tab-unfocused-occupied
  `((t :inherit tab-bar-tab-inactive :overline t))
    "Tab bar face for unfocused tabs that are occupied."
    :group 'tab-bar-faces)
(defface tab-bar-tab-focused-empty
  `((t :inherit tab-bar-tab))
    "Tab bar face for focused tabs that are empty."
    :group 'tab-bar-faces)
(defface tab-bar-tab-unfocused-empty
  `((t :inherit tab-bar-tab-inactive))
    "Tab bar face for unfocused tabs that are empty."
    :group 'tab-bar-faces)

(custom-theme-set-variables
 'anemofilia
 '(overline-margin 0))

(custom-theme-set-faces
 'anemofilia

 `(mode-line ((t (:background ,darker-gray :foreground ,blue :box (:color ,dark-gray)))))
 `(mode-line-buffer-id ((t (:weight normal))))
 `(mode-line-emphasis ((t (:weight bold))))
 `(mode-line-highlight ((t (:background ,darker-gray))))
 `(mode-line-inactive ((t (:background ,darker-gray :foreground "dim gray"))))

 `(tab-bar ((t (:background ,normal-bg :foreground ,normal-bg :box (:line-width -1 :color ,dark-gray)))))
 `(tab-bar-tab ((t (:background ,focused-bg :foreground ,focused-fg))))
 `(tab-bar-tab-inactive ((t (:background ,normal-bg :foreground ,normal-fg))))
 `(tab-bar-tab-highlight ((t (:background ,focused-bg))))

 `(eat-term-color-0 ((t (:background ,black :foreground ,black))))
 `(eat-term-color-1 ((t (:background ,red :foreground ,red))))
 `(eat-term-color-2 ((t (:background ,green :foreground ,green))))
 `(eat-term-color-3 ((t (:background ,yellow :foreground ,yellow))))
 `(eat-term-color-4 ((t (:background ,blue :foreground ,blue))))
 `(eat-term-color-5 ((t (:background ,magenta :foreground ,magenta))))
 `(eat-term-color-6 ((t (:background ,cyan :foreground ,cyan))))
 `(eat-term-color-7 ((t (:background ,white :foreground ,white))))
 `(eat-term-color-8 ((t (:background ,gray :foreground ,gray))))
 `(eat-term-color-9 ((t (:inherit eat-term-color-1))))
 `(eat-term-color-10 ((t (:inherit eat-term-color-2))))
 `(eat-term-color-11 ((t (:inherit eat-term-color-3))))
 `(eat-term-color-12 ((t (:inherit eat-term-color-4))))
 `(eat-term-color-13 ((t (:inherit eat-term-color-5))))
 `(eat-term-color-14 ((t (:inherit eat-term-color-6))))
 `(eat-term-color-15 ((t (:inherit eat-term-color-7))))

 `(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground ,blue))))
 `(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground ,red))))
 `(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground ,cyan))))
 `(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground ,yellow))))
 `(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground ,magenta))))
 `(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground ,green))))
 `(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground ,gray))))
 `(rainbow-delimiters-unmatched-face ((t (:inherit default))))
 `(rainbow-delimiters-mismatched-face ((t (:inherit default))))
 `(rainbow-delimiters-base-error-face ((default (:inherit (rainbow-delimiters-base-face))) (t (:foreground ,red))))

 `(org-document-title ((t (:height 1.2 :underline nil :inherit org-level-1))))
 `(org-level-1 ((t (:inherit default :extend t :foreground ,white :height 1.1 :family "Sans Serif"))))
 `(org-level-2 ((t (:family "Sans Serif" :height 1.0 :foreground ,white :extend t :inherit default))))
 `(org-level-3 ((t (:foreground ,white :extend t :inherit default))))
 `(org-level-4 ((t (:inherit default :extend t :foreground ,white))))
 `(org-level-5 ((t (:inherit default :extend t :foreground ,white))))
 `(org-level-6 ((t (:extend t :foreground ,white :inherit (default)))))
 `(org-level-7 ((t (:extend t :foreground ,white :inherit (default)))))
 `(org-level-8 ((t (:extend t :foreground ,white :inherit (default)))))
 `(org-todo ((t (:foreground ,green :weight bold))))
 `(org-done ((t (:foreground ,red :weight bold))))
 `(org-table ((t (:foreground ,white))))
 `(org-ellipsis ((t (:foreground ,white))))
 `(org-block-begin-line ((t (:background ,blue :extend t :inherit \#fff))))
 `(org-block-end-line ((t (:inherit \#fff :extend t :background ,blue))))
 `(org-scheduled ((t (:foreground ,blue :weight bold))))
 `(org-date ((t (:underline (:color foreground-color :style line) :foreground ,blue))))
 `(org-tag ((t (:bold t))))
 `(org-warning ((t (:inherit font-lock-warning-face))))
 `(org-headline-todo ((t (:foreground ,white))))
 `(org-sexp-date ((t (:foreground ,white))))
 `(org-agenda-date ((t (:foreground ,white))))
 `(org-date-selected ((t (:foreground ,white :inverse-video t))))
 `(org-footnote ((t (:underline (:color foreground-color :style line) :style nil :foreground ,blue))))
 `(org-agenda-date-today ((t (:inherit org-agenda-date :foreground "#444083" :weight bold))))
 `(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "#444083" :weight bold))))
 `(org-formula ((t (:foreground ,yellow))))
 `(org-scheduled-previously ((t (:foreground ,yellow))))
 `(org-upcoming-deadline ((t (:foreground ,yellow :weight bold))))
 `(org-document-info ((t (:foreground ,white))))
 `(org-drawer ((t (:foreground ,white))))
 `(org-latex-and-related ((t (:foreground ,white))))
 `(org-scheduled-today ((t (:foreground ,yellow :weight ultra-bold))))
 `(org-time-grid ((t (:foreground ,blue))))


 `(cursor ((t (:background ,blue :foreground ,white))))
 `(fixed-pitch ((t (:family "Monospace"))))
 `(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 `(escape-glyph ((t (:background "#444083" :foreground ,yellow))))
 `(homoglyph ((t (:foreground ,yellow))))
 `(minibuffer-prompt ((t (:foreground ,blue))))
 `(highlight ((t (:background ,blue :foreground ,black))))
 `(region ((t (:extend t :background "#1F102f"))))
 `(shadow ((t (:foreground ,white))))
 `(secondary-selection ((t (:extend t :background ,darker-gray))))

 `(font-lock-builtin-face ((t (:foreground "#ffd17a"))))
 `(font-lock-comment-delimiter-face ((t (:foreground "#86adff"))))
 `(font-lock-comment-face ((t (:foreground "#86adff"))))
 `(font-lock-constant-face ((t (:foreground "#df6760"))))
 `(font-lock-doc-face ((t (:foreground "#9a99e7" :inherit font-lock-string-face))))
 `(font-lock-function-name-face ((t (:foreground "#86adff"))))
 `(font-lock-keyword-face ((t (:foreground ,blue))))
 `(font-lock-negation-char-face ((t nil)))
 `(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 `(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 `(font-lock-regexp-grouping-construct ((t (:inherit bold))))
 `(font-lock-string-face ((t (:foreground "#fc97ff"))))
 `(font-lock-type-face ((t (:foreground "#ffd17a"))))
 `(font-lock-variable-name-face ((t nil)))
 `(font-lock-warning-face ((t (:foreground "#dce081" :weight bold))))

 `(button ((t (:inherit (link)))))
 `(link ((t (:foreground ,blue :underline (:color foreground-color :style line)))))
 `(link-visited ((t (:foreground ,white :inherit link))))
 `(fringe ((t (:foreground "#506080" :background ,darker-gray))))
 ;`(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background ,white)) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground ,white :background "black"))))
 `(tooltip ((t (:foreground "#FFFFFF" :background "#5f5e8a"))))
 `(isearch ((t (:foreground ,white :background "#5533AA"))))
 `(isearch-fail ((t (:foreground ,gray))))
 `(lazy-highlight ((t (:inherit default :background ,blue))))
 `(match ((t (:background ,blue :foreground ,white))))
 `(next-error ((t (:inherit (region)))))
 `(query-replace ((t (:inherit isearch :background ,yellow :foreground "#101010"))))
 `(line-number-current-line ((t (:inherit line-number :background ,darker-gray :foreground ,blue))))
 `(line-number ((t (:inherit (shadow default)))))
 `(line-number-major-tick ((((class color grayscale) (background light)) (:bold t :background "grey85")) (((class color grayscale) (background dark)) (:bold t :background "grey75")) (t (:inherit (line-number)))))
 
 `(whitespace-space ((t (:foreground "#808080"))))
 `(whitespace-hspace ((t (:inherit whitespace-space))))
 `(whitespace-tab ((t (:inherit whitespace-space))))
 `(whitespace-newline ((t (:inherit whitespace-space))))
 `(whitespace-trailing ((t (:inherit whitespace-space))))
 `(whitespace-space-before-tab ((t (:inherit whitespace-space))))
 `(whitespace-indentation ((t (:inherit whitespace-space))))
 `(whitespace-big-indent ((t (:inherit whitespace-space))))
 `(whitespace-empty ((t (:extend t :inherit whitespace-space))))
 `(whitespace-space-after-tab ((t (:inherit whitespace-space))))
 `(whitespace-missing-newline-at-eof ((t (:inherit whitespace-space))))
 `(whitespace-line ((t nil)))
 `(trailing-whitespace ((t (:inherit whitespace-space))))
 `(nobreak-space ((t (:inherit whitespace-space))))

 `(fill-column-indicator ((t (:foreground ,dark-gray :background ,dark-gray))))
 `(hl-fill-column-face ((t (:background ,dark-gray))))
 `(hl-line ((t (:inherit fill-column-indicator))))
 `(eros-result-overlay-face ((t (:foreground ,gray))))
 `(geiser-font-lock-repl-output ((t (:foreground ,white))))
 `(corfu-current ((t (:background ,blue :foreground ,white))))
 `(show-paren-match ((t (:overline t :weight ultra-heavy :width extra-expanded))))
 `(orderless-match-face-0 ((t (:weight bold))))
 `(orderless-match-face-1 ((t (:inherit orderless-match-face-0))))
 `(orderless-match-face-2 ((t (:inherit orderless-match-face-0))))
 `(orderless-match-face-3 ((t (:inherit orderless-match-face-0))))
 `(vertico-current ((t (:extend t :inherit (highlight)))))
 `(default ((t (:inherit nil :extend nil :stipple nil :background "#101010" :foreground "#f0f0f0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :foundry "PfEd" :family "Monospace")))))

(provide-theme 'anemofilia)
