# Accounts

[lgcoelho@disroot.org]
source   = imaps://lgcoelho%40disroot.org@disroot.org:993
outgoing = smtp://lgcoelho%40disroot.org@disroot.org:587
source-cred-cmd = cat $XDG_RUNTIME_DIR/secrets/aerc/disroot/lgcoelho/password
outgoing-cred-cmd = cat $XDG_RUNTIME_DIR/secrets/aerc/disroot/lgcoelho/password
default  = INBOX
from     = Luis Guilherme Coelho <lgcoelho@disroot.org>
copy-to  = Sent
check-mail = 2m

[anemofilia@disroot.org]
source   = imaps://anemofilia%40disroot.org@disroot.org:993
outgoing = smtp://anemofilia%40disroot.org@disroot.org:587
source-cred-cmd = cat $XDG_RUNTIME_DIR/secrets/aerc/disroot/anemofilia/password
outgoing-cred-cmd = cat $XDG_RUNTIME_DIR/secrets/aerc/disroot/anemofilia/password
default  = INBOX
from     = Anemofilia <anemofilia@disroot.org>
copy-to  = Sent
check-mail = 2m
