# Set default terminal colors 
set-option -ga terminal-overrides ",foot:Tc"
set -g default-terminal "foot"
set -g focus-event on

# Set history limit
set -g history-limit 100000

# Source config file 
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf"

# Plugins 
set -g @plugin 'whame/tmux-modal'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.config/tmux/plugins/tpm/tpm'

# Ask for confirmation before executing risky commands
set -g @modal-yesno-cmd on

# Use keybindings set in ~/.config/tmux/keybindings.conf
set -g @modal-keybindings-conf ~/.config/tmux/keybindings.conf 

# Start on modal command mode
set -g @modal-on-start on

# Change pane navigation
bind -n M-h if -F '#{pane_at_left}' '' 'select-pane -L'
bind -n M-j if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind -n M-k if -F '#{pane_at_top}' '' 'select-pane -U'
bind -n M-l if -F '#{pane_at_right}' '' 'select-pane -R'

# Change pane resize
bind -n M-H resize-pane -L
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U
bind -n M-L resize-pane -R

# set -g allow-passthrough on

# Window
set -g base-index 1

# Pane
set -g pane-base-index 1
set -g display-panes-colour "#303030"
set -g display-panes-active-colour blue
set -g pane-border-style fg="#303030"
set -g pane-active-border-style fg=blue
set -g pane-border-lines single
set -g pane-border-format ""
set -g pane-border-status top

# Status bar
set -g status on
set -g status-justify left
set -g status-interval 40
set -g status-keys vi
set -g status-position top

set -g status-style fg=blue,bg="#303030"
#set -g status-right ""
setw -g window-status-current-style fg="#303030",bright,bg=blue
setw -g window-status-separator "#[fg=brightblack]|#[default]"

set -g message-style fg=white,bg="#1d1b2a"
set -g message-command-style fg="#1d1b2a",bg=white

set -g popup-style fg=default,bright,bg="#423D56"

set -g mode-style fg=black,bright,bg=blue
set -g status-right "#[fg=default,bright,bg=default]#(tmux-mem-cpu-load -a2 -g0)"
