# SSS - Supreme Sexp System

# Copyright © Josep Bigorra <jjbigorra@gmail.com>

# sss is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# sss is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with sss.  If not, see <https://www.gnu.org/licenses/>.

variables:
  - &submit_job_image 'docker.io/jjba23/byggsteg-woodpecker-submit-job:v0.1.32'
  - &poll_job_image 'docker.io/jjba23/byggsteg-woodpecker-poll-job:v0.1.32'
  - &get_token_image 'docker.io/jjba23/byggsteg-woodpecker-get-token:v0.1.32'
  - &jointhefreeworld_byggsteg_url 'https://byggsteg.jointhefreeworld.org'
  - &main_branch 'trunk'

clone:
  - name: "⬇️ Clone Git repository"
    image: woodpeckerci/plugin-git
    settings:
      depth: 1

steps:
  get-byggsteg-token:
    name: "🔒 Get token @ Byggsteg"
    image: *get_token_image
    when:
      - event: [ push ]
        branch: [ *main_branch ]
    settings:
      BYGGSTEG_EMAIL:
        from_secret: BYGGSTEG_EMAIL
      BYGGSTEG_PASSWORD:
        from_secret: BYGGSTEG_PASSWORD
      BYGGSTEG_URL: *jointhefreeworld_byggsteg_url

  submit-byggsteg-job:
    name: "💼 Submit job @ Byggsteg"
    image: *submit_job_image
    when:
      - event: [ push ]
        branch: [ *main_branch ]
    settings:
      BYGGSTEG_URL: *jointhefreeworld_byggsteg_url
      BYGGSTEG_JOB_CODE: |
        (lambda()
          `((task . ("maak-test" "maak-deploy"))
            (project . "%%CI_REPO_NAME%%")
            (branch-name . "%%CI_COMMIT_BRANCH%%")
            (clone-url . "%%CI_REPO_CLONE_URL%%")
            (env . ((VERITAS_REPORTER . monotone-reporter)))))

  poll-byggsteg-job:
    name: "🔄 Poll job status @ Byggsteg"
    image: *poll_job_image
    when:
      - event: [ push ]
        branch: [ *main_branch ]
    settings:
      BYGGSTEG_URL: *jointhefreeworld_byggsteg_url
