osd-font="DejaVu Sans Mono"
osd-font-size=36
osd-scale=0.8

sub-font="DejaVu Serif"
sub-font-size=36
sub-border-size=5
sub-ass-style-overrides=Outline=2.5

[1600p]
ytdl-format=bestvideo[height<=?1600]+bestaudio/best
