osd-font="DejaVu Sans Mono"
osd-font-size=36
osd-scale=0.8

sub-font="DejaVu Serif"
sub-font-size=42
sub-border-style=background-box
sub-back-color=0/0

[1600p]
ytdl-format=bestvideo[height<=?1600]+bestaudio/best
